// AUTO-GENERATED by .bambeh-ops/patch.ps1
export class NetworkError extends Error {
  constructor(public url: string, public cause?: unknown) {
    super(Network request failed: + url);
    this.name = "NetworkError";
  }
}
const TIMEOUT_MS = 30000;
const _origFetch = globalThis.fetch.bind(globalThis);
globalThis.fetch = (async (input: RequestInfo | URL, init: RequestInit = {}) => {
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    return await _origFetch(input, { ...init, signal: init.signal ?? ctrl.signal });
  } catch (e) {
    const url = typeof input === "string" ? input : (input as URL).toString();
    console.error("[net]", url, e);
    throw new NetworkError(url, e);
  } finally { clearTimeout(t); }
}) as typeof fetch;
export {};