/**
 * src/hooks/useAppLang.ts — Bambeh Marketplace
 *
 * Drop-in replacement for the existing hook.
 * Bridges the LanguageContext to the { useLang, t } API used by FarmFresh pages.
 *
 * Usage (same as before):
 *   const lang = useLang();
 *   const label = t("catAll", lang);   // "All" | "Tout" | "All" | "الكل" | "Fof"
 *
 * The `t()` export is a standalone function so it can be called outside components
 * (e.g. in array literals at module scope). It does NOT call hooks.
 */

import { useLanguage } from "@/context/LanguageContext";

// Re-export the language code type
export type LangCode = "en" | "fr" | "pidgin" | "ar" | "ff";

// ─── Hook: returns the current language code ──────────────────────────────────
export function useLang(): LangCode {
  const { language } = useLanguage();
  return language as LangCode;
}

// ─── Standalone translation lookup ────────────────────────────────────────────
// Translations are co-located here so t() works without the React context.
const translations: Record<string, Record<string, string | ((...args: any[]) => string)>> = {
  en: {
    home: "Home",
    jobs: "Jobs",
    marketplace: "Marketplace",
    services: "Services",
    rentals: "Rentals",
    vehicles: "Vehicles",
    exchange: "Exchange",
    community: "Community",
    sell: "Sell",
    buy: "Buy",
    search: "Search",
    login: "Login",
    register: "Register",
    logout: "Logout",
    settings: "Settings",
    favorites: "Favorites",
    orders: "Orders",
    next: "Next",
    submit: "Submit",
    back: "Back",
    cancel: "Cancel",
    save: "Save",
    loading: "Loading…",
    error: "Something went wrong. Please try again.",
    retry: "Retry",
    seeAll: "See all",

    farmFresh: "Farm Fresh",
    searchPlaceholder: "Search produce, location…",
    noProduceFound: "No produce found",
    listYourProduce: "List Your Produce",
    realListings: (n: number) => `${n} listing${n !== 1 ? "s" : ""} from local farmers`,
    showingSamples: (n: number) => `Showing ${n} sample listings`,
    buyDirect: "Buy Direct From Farmers",
    buyDirectSub: "Fresh produce, fair prices, from farm to your table in Cameroon.",
    joinGroup: "Join Group Buy",
    organic: "Organic",
    noPhotoYet: "No photo yet",
    addToCart: "Add to Cart",
    added: "Added ✓",
    views: "views",
    cart: "Cart",
    orderNow: "Order Now",
    quantity: "Qty",
    loading2: "Loading…",

    catAll: "All",
    catVegetables: "Vegetables",
    catFruits: "Fruits",
    catTubers: "Tubers",
    catGrains: "Grains",
    catLegumes: "Legumes",
    catHerbs: "Herbs",
    catDairy: "Dairy",

    aboutProduct: "About This Product",
    unit: "Unit",
    locationKey: "Location",
    deliveryKey: "Delivery",
    delivAvail: "Available",
    pickupOnly: "Pickup only",
    stockKey: "In Stock",
    yourFarmer: "Your Farmer",
    whatsappSeller: "WhatsApp Farmer",
    moreFarm: "More Farm Products",
    shareProduct: "Share This Product",
    shareWhatsApp: "Share on WhatsApp",
    copyLink: "Copy Link",
    freshnessGuarantee: "Freshness Guarantee",
    freshnessDesc: "If your produce arrives below standard, report within 24 hours and we'll arrange a replacement or full refund.",
    productNotFound: "Product Not Found",
    productNotFoundSub: "This product may be unavailable or has been removed.",
    backToFarmFresh: "Back to Farm Fresh",

    orderSummary: "Order Summary",
    deliveryAddress: "Delivery Address",
    deliveryAddressPlaceholder: "Quarter, street, landmark…",
    contactPhone: "Contact Phone",
    orderNotes: "Notes for Farmer (optional)",
    orderNotesPlaceholder: "Preferred delivery time, special instructions…",
    placeOrder: "Place Order",
    orderSuccess: "Order Placed!",
    orderSuccessSub: "The farmer will contact you shortly to confirm delivery.",
    orderError: "Order Failed",
    demoOrderNote: "This is a demo product. In production, your order goes to a real farmer.",
    totalAmount: "Total",
    transactionFee: "Transaction Fee (1%)",
    grandTotal: "Grand Total",

    sellProduce: "List Your Produce",
    step1: "Produce Details",
    step2: "Location & Description",
    step3: "Photos & Review",
    productName: "Product Name",
    category: "Category",
    pricePerUnit: "Price per Unit (FCFA)",
    unitLabel: "Unit",
    isOrganic: "This produce is organic / naturally grown",
    availableForDelivery: "Available for delivery",
    description: "Description",
    descriptionPlaceholder: "Describe freshness, quality, harvest date…",
    locationLabel: "Your Location (Town / Quarter)",
    locationPlaceholder: "e.g. Bamenda, Nkwen Quarter",
    photos: "Photos (up to 4)",
    addPhoto: "Add Photo",
    reviewListing: "Review & Submit",
    submitListing: "Post Listing",
    listingSuccess: "Listing Published!",
    listingSuccessSub: "Your produce is now live. Buyers can see and order it.",
    saveDraft: "Save Draft",
    draftSaved: "Draft saved",
    photoError: "Only JPG, PNG or WebP, max 5 MB each.",
    fillRequired: "Please fill in all required fields.",

    cartEmpty: "Your cart is empty",
    continueShopping: "Continue Shopping",
    checkout: "Checkout",
    subtotal: "Subtotal",
    fee1pct: "Bambeh Fee (1%)",
    total: "Total",

    groupBuyingAd: {
      title: "Group Buying — Save Together",
      subtitle: "Pool orders with neighbours and get better prices.",
      cta: "Join Now",
    } as any,
    sellProduceAd: {
      title: "Are You a Farmer?",
      subtitle: "List your produce in 3 minutes and reach buyers across Cameroon.",
      cta: "Start Selling",
    } as any,
  },

  fr: {
    home: "Accueil",
    jobs: "Emplois",
    marketplace: "Marché",
    services: "Services",
    rentals: "Locations",
    sell: "Vendre",
    buy: "Acheter",
    search: "Rechercher",
    login: "Connexion",
    register: "S'inscrire",
    logout: "Déconnexion",
    settings: "Paramètres",
    favorites: "Favoris",
    orders: "Commandes",
    next: "Suivant",
    submit: "Soumettre",
    back: "Retour",
    cancel: "Annuler",
    save: "Enregistrer",
    loading: "Chargement…",
    error: "Une erreur est survenue.",
    retry: "Réessayer",
    seeAll: "Voir tout",

    farmFresh: "Ferme Fraîche",
    searchPlaceholder: "Chercher un produit, une ville…",
    noProduceFound: "Aucun produit trouvé",
    listYourProduce: "Publier votre produit",
    realListings: (n: number) => `${n} produit${n !== 1 ? "s" : ""} d'agriculteurs locaux`,
    showingSamples: (n: number) => `${n} exemples de produits`,
    buyDirect: "Achetez Directement aux Agriculteurs",
    buyDirectSub: "Produits frais, prix équitables, de la ferme à votre table.",
    joinGroup: "Rejoindre un groupe d'achat",
    organic: "Bio",
    noPhotoYet: "Pas de photo",
    addToCart: "Ajouter au panier",
    added: "Ajouté ✓",
    views: "vues",
    cart: "Panier",
    orderNow: "Commander",
    quantity: "Qté",

    catAll: "Tout",
    catVegetables: "Légumes",
    catFruits: "Fruits",
    catTubers: "Tubercules",
    catGrains: "Céréales",
    catLegumes: "Légumineuses",
    catHerbs: "Herbes",
    catDairy: "Produits laitiers",

    aboutProduct: "À propos du produit",
    unit: "Unité",
    locationKey: "Lieu",
    deliveryKey: "Livraison",
    delivAvail: "Disponible",
    pickupOnly: "Récupération uniquement",
    stockKey: "En stock",
    yourFarmer: "Votre Agriculteur",
    whatsappSeller: "WhatsApp Agriculteur",
    moreFarm: "Plus de produits",
    shareProduct: "Partager ce produit",
    shareWhatsApp: "Partager sur WhatsApp",
    copyLink: "Copier le lien",
    freshnessGuarantee: "Garantie de fraîcheur",
    freshnessDesc: "Si vos produits arrivent dégradés, signalez-le en 24 h pour un remplacement ou remboursement.",
    productNotFound: "Produit introuvable",
    productNotFoundSub: "Ce produit est peut-être supprimé.",
    backToFarmFresh: "Retour à Ferme Fraîche",

    orderSummary: "Récapitulatif",
    deliveryAddress: "Adresse de livraison",
    deliveryAddressPlaceholder: "Quartier, rue, repère…",
    contactPhone: "Téléphone",
    orderNotes: "Notes (facultatif)",
    orderNotesPlaceholder: "Heure de livraison, instructions…",
    placeOrder: "Confirmer la commande",
    orderSuccess: "Commande passée !",
    orderSuccessSub: "L'agriculteur vous contactera bientôt.",
    orderError: "Échec",
    demoOrderNote: "Produit de démonstration.",
    totalAmount: "Total",
    transactionFee: "Frais Bambeh (1 %)",
    grandTotal: "Total général",

    sellProduce: "Publier un produit",
    step1: "Détails",
    step2: "Lieu & Description",
    step3: "Photos & Vérification",
    productName: "Nom du produit",
    category: "Catégorie",
    pricePerUnit: "Prix par unité (FCFA)",
    unitLabel: "Unité",
    isOrganic: "Produit bio / naturel",
    availableForDelivery: "Livraison disponible",
    description: "Description",
    descriptionPlaceholder: "Fraîcheur, qualité, date de récolte…",
    locationLabel: "Lieu (Ville / Quartier)",
    locationPlaceholder: "ex. Bafoussam, Quartier Tamdja",
    photos: "Photos (jusqu'à 4)",
    addPhoto: "Ajouter une photo",
    reviewListing: "Vérifier et soumettre",
    submitListing: "Publier",
    listingSuccess: "Annonce publiée !",
    listingSuccessSub: "Votre produit est visible.",
    saveDraft: "Brouillon",
    draftSaved: "Brouillon sauvegardé",
    photoError: "JPG, PNG ou WebP, max 5 Mo.",
    fillRequired: "Remplissez tous les champs requis.",

    cartEmpty: "Panier vide",
    continueShopping: "Continuer",
    checkout: "Passer à la caisse",
    subtotal: "Sous-total",
    fee1pct: "Frais Bambeh (1 %)",
    total: "Total",

    groupBuyingAd: {
      title: "Achat groupé — Économisez ensemble",
      subtitle: "Groupez vos commandes pour de meilleurs prix.",
      cta: "Rejoindre",
    } as any,
    sellProduceAd: {
      title: "Vous êtes agriculteur ?",
      subtitle: "Publiez en 3 minutes et atteignez les acheteurs partout.",
      cta: "Commencer à vendre",
    } as any,
  },

  pidgin: {
    home: "Home",
    farmFresh: "Farm Fresh",
    searchPlaceholder: "Find food, place…",
    noProduceFound: "No food dey",
    listYourProduce: "List Your Tins",
    realListings: (n: number) => `${n} listing${n !== 1 ? "s" : ""} dey from farmers`,
    showingSamples: (n: number) => `${n} sample listing${n !== 1 ? "s" : ""} dey show`,
    buyDirect: "Buy Direct From Farmer",
    buyDirectSub: "Fresh food, good price, from farm reach your house.",
    joinGroup: "Join Group Buy",
    organic: "Organic",
    noPhotoYet: "No photo yet",
    addToCart: "Add for Cart",
    added: "E dey inside ✓",
    views: "views",
    cart: "Cart",
    orderNow: "Order Now",
    quantity: "How Many",
    back: "Back",
    cancel: "Cancel",
    loading: "E dey load…",
    seeAll: "See all",
    sell: "Sell",

    catAll: "All",
    catVegetables: "Vegetables",
    catFruits: "Fruits",
    catTubers: "Tubers",
    catGrains: "Grains",
    catLegumes: "Legumes",
    catHerbs: "Herbs",
    catDairy: "Dairy",

    aboutProduct: "About Dis Tin",
    unit: "Unit",
    locationKey: "Place",
    deliveryKey: "Delivery",
    delivAvail: "E dey available",
    pickupOnly: "Come take am",
    stockKey: "Quantity",
    yourFarmer: "Your Farmer",
    whatsappSeller: "WhatsApp the Farmer",
    moreFarm: "More Farm Tins",
    shareProduct: "Share Dis Tin",
    shareWhatsApp: "Share for WhatsApp",
    copyLink: "Copy Link",
    freshnessGuarantee: "Freshness Guarantee",
    freshnessDesc: "If your food no fresh when e reach, report am for 24 hours, we go fix am.",
    productNotFound: "Dis Product No Dey",
    productNotFoundSub: "E don remove or no available again.",
    backToFarmFresh: "Back to Farm Fresh",

    orderSummary: "Order Summary",
    deliveryAddress: "Where dem go bring am",
    deliveryAddressPlaceholder: "Quarter, street, landmark…",
    contactPhone: "Your phone number",
    orderNotes: "Tell farmer something (optional)",
    orderNotesPlaceholder: "When you want am…",
    placeOrder: "Place Order",
    orderSuccess: "Order Don Go!",
    orderSuccessSub: "Farmer go call you soon.",
    orderError: "Order fail",
    demoOrderNote: "Na demo product.",
    totalAmount: "Total",
    transactionFee: "Bambeh Fee (1%)",
    grandTotal: "Grand Total",

    sellProduce: "Post Your Produce",
    step1: "Product Details",
    step2: "Place & Description",
    step3: "Photos & Review",
    productName: "Product Name",
    category: "Category",
    pricePerUnit: "Price (FCFA)",
    unitLabel: "Unit",
    isOrganic: "Na organic food",
    availableForDelivery: "You fit deliver am",
    description: "Description",
    descriptionPlaceholder: "Talk about freshness, quality…",
    locationLabel: "Your Place",
    locationPlaceholder: "e.g. Bamenda, Nkwen",
    photos: "Photos (up to 4)",
    addPhoto: "Add Photo",
    reviewListing: "Check and Submit",
    submitListing: "Post Am",
    listingSuccess: "Listing Don Post!",
    listingSuccessSub: "Your produce dey live.",
    saveDraft: "Save Draft",
    draftSaved: "Draft saved",
    photoError: "Only JPG, PNG or WebP, max 5 MB.",
    fillRequired: "Fill all fields abeg.",

    cartEmpty: "Your cart empty",
    continueShopping: "Continue Shopping",
    checkout: "Go Pay",
    subtotal: "Subtotal",
    fee1pct: "Bambeh Fee (1%)",
    total: "Total",

    groupBuyingAd: {
      title: "Group Buy — Save Together",
      subtitle: "Pool orders with your people for better prices.",
      cta: "Join Now",
    } as any,
    sellProduceAd: {
      title: "You be Farmer?",
      subtitle: "Post your produce in 3 minutes, reach buyers everywhere.",
      cta: "Start Sell",
    } as any,
  },

  ar: {
    home: "الرئيسية",
    farmFresh: "منتجات الحقل",
    searchPlaceholder: "ابحث عن منتج أو موقع…",
    noProduceFound: "لا توجد منتجات",
    listYourProduce: "أضف منتجك",
    realListings: (n: number) => `${n} منتج${n !== 1 ? "ات" : ""} من المزارعين`,
    showingSamples: (n: number) => `عرض ${n} نماذج`,
    buyDirect: "اشترِ مباشرة من المزارع",
    buyDirectSub: "منتجات طازجة وأسعار عادلة من المزرعة إلى مائدتك.",
    joinGroup: "انضم للشراء الجماعي",
    organic: "عضوي",
    noPhotoYet: "لا توجد صورة",
    addToCart: "أضف إلى السلة",
    added: "تمت الإضافة ✓",
    views: "مشاهدات",
    cart: "السلة",
    orderNow: "اطلب الآن",
    quantity: "الكمية",
    back: "رجوع",
    cancel: "إلغاء",
    loading: "جارٍ التحميل…",
    seeAll: "عرض الكل",
    sell: "بيع",

    catAll: "الكل",
    catVegetables: "خضروات",
    catFruits: "فواكه",
    catTubers: "درنات",
    catGrains: "حبوب",
    catLegumes: "بقوليات",
    catHerbs: "أعشاب",
    catDairy: "منتجات الألبان",

    aboutProduct: "حول هذا المنتج",
    unit: "الوحدة",
    locationKey: "الموقع",
    deliveryKey: "التوصيل",
    delivAvail: "متاح",
    pickupOnly: "الاستلام الشخصي فقط",
    stockKey: "المخزون",
    yourFarmer: "مزارعك",
    whatsappSeller: "تواصل عبر واتساب",
    moreFarm: "مزيد من المنتجات",
    shareProduct: "مشاركة هذا المنتج",
    shareWhatsApp: "مشاركة على واتساب",
    copyLink: "نسخ الرابط",
    freshnessGuarantee: "ضمان النضارة",
    freshnessDesc: "إذا وصلت منتجاتك دون المستوى، أبلغ خلال 24 ساعة للاستبدال أو الاسترداد.",
    productNotFound: "المنتج غير موجود",
    productNotFoundSub: "قد يكون هذا المنتج غير متاح.",
    backToFarmFresh: "العودة إلى منتجات الحقل",

    orderSummary: "ملخص الطلب",
    deliveryAddress: "عنوان التوصيل",
    deliveryAddressPlaceholder: "الحي، الشارع، معلم…",
    contactPhone: "رقم الهاتف",
    orderNotes: "ملاحظات (اختياري)",
    orderNotesPlaceholder: "وقت التسليم، تعليمات خاصة…",
    placeOrder: "تأكيد الطلب",
    orderSuccess: "تم تقديم الطلب!",
    orderSuccessSub: "سيتواصل معك المزارع قريباً.",
    orderError: "فشل تقديم الطلب",
    demoOrderNote: "هذا منتج تجريبي.",
    totalAmount: "الإجمالي",
    transactionFee: "رسوم بامبيه (1٪)",
    grandTotal: "الإجمالي الكلي",

    sellProduce: "أضف منتجك",
    step1: "تفاصيل المنتج",
    step2: "الموقع والوصف",
    step3: "الصور والمراجعة",
    productName: "اسم المنتج",
    category: "الفئة",
    pricePerUnit: "السعر لكل وحدة (FCFA)",
    unitLabel: "الوحدة",
    isOrganic: "منتج عضوي",
    availableForDelivery: "متاح للتوصيل",
    description: "الوصف",
    descriptionPlaceholder: "صف الجودة وتاريخ الحصاد…",
    locationLabel: "موقعك",
    locationPlaceholder: "مثال: ياوندي، الحي الجامعي",
    photos: "الصور (حتى 4)",
    addPhoto: "إضافة صورة",
    reviewListing: "مراجعة وإرسال",
    submitListing: "نشر الإعلان",
    listingSuccess: "تم نشر الإعلان!",
    listingSuccessSub: "منتجك ظاهر الآن للمشترين.",
    saveDraft: "حفظ المسودة",
    draftSaved: "تم حفظ المسودة",
    photoError: "يُسمح فقط بـ JPG أو PNG أو WebP، بحد أقصى 5 ميغابايت.",
    fillRequired: "يرجى ملء جميع الحقول.",

    cartEmpty: "سلتك فارغة",
    continueShopping: "متابعة التسوق",
    checkout: "إتمام الشراء",
    subtotal: "المجموع الجزئي",
    fee1pct: "رسوم بامبيه (1٪)",
    total: "الإجمالي",

    groupBuyingAd: {
      title: "الشراء الجماعي — وفّروا معاً",
      subtitle: "جمّعوا طلباتكم للحصول على أسعار أفضل.",
      cta: "انضم الآن",
    } as any,
    sellProduceAd: {
      title: "هل أنت مزارع؟",
      subtitle: "أضف منتجاتك في 3 دقائق وصل إلى المشترين.",
      cta: "ابدأ البيع",
    } as any,
  },

  ff: {
    home: "Jeyeendi",
    farmFresh: "Liɓɓi Ɗowi",
    searchPlaceholder: "Ƴeew liɓɓi, gure…",
    noProduceFound: "Liɓɓi alaa",
    listYourProduce: "Naattin Liɓɓi Maa",
    realListings: (n: number) => `${n} liɓɓi daneeli`,
    showingSamples: (n: number) => `Misaale ${n} liɓɓi`,
    buyDirect: "Soodee Fewndo Winndiyanke",
    buyDirectSub: "Liɓɓi daneeli, njamndi yooɓii.",
    joinGroup: "Naatir Ƴoorgo",
    organic: "Daano",
    noPhotoYet: "Sawru alaa",
    addToCart: "Naattin Sagas",
    added: "E nder ✓",
    views: "yiyiiko",
    cart: "Sagas",
    orderNow: "Sarwii Ɗoo",
    quantity: "Timmol",
    back: "Heddii",
    cancel: "Haɗ",
    loading: "E nder loodi…",
    seeAll: "Hol fof",
    sell: "Fiyee",

    catAll: "Fof",
    catVegetables: "Leɗɗe",
    catFruits: "Biɗɗo",
    catTubers: "Yonnde",
    catGrains: "Ganɗal",
    catLegumes: "Kuɓɓe",
    catHerbs: "Caali",
    catDairy: "Kosam",

    aboutProduct: "Dow Nde Nii",
    unit: "Wondirde",
    locationKey: "Nokku",
    deliveryKey: "Artirde",
    delivAvail: "Waawi",
    pickupOnly: "Ar Usee",
    stockKey: "E junngo",
    yourFarmer: "Winndiyanke Maa",
    whatsappSeller: "WhatsApp Winndiyanke",
    moreFarm: "Liɓɓi Ɗuuɗɗi",
    shareProduct: "Siiwtindiraa Nde Nii",
    shareWhatsApp: "Siiwtindiraa WhatsApp",
    copyLink: "Natto Laawol",
    freshnessGuarantee: "Ceertol Daneeli",
    freshnessDesc: "So liɓɓi maa waɗaani daneeli, neldee 24 waktu min neldoyii.",
    productNotFound: "Liɓɓi Alaa",
    productNotFoundSub: "Liɓɓi hee wudii.",
    backToFarmFresh: "Heddii Liɓɓi Ɗowi",

    orderSummary: "Sarwii Tiimii",
    deliveryAddress: "Nokku Artirde",
    deliveryAddressPlaceholder: "Saare, laawol…",
    contactPhone: "Telefon",
    orderNotes: "Haala (seeɗa)",
    orderNotesPlaceholder: "Waktu artirde…",
    placeOrder: "Neld Sarwii",
    orderSuccess: "Sarwii Neldii!",
    orderSuccessSub: "Winndiyanke wiiloyaa maa.",
    orderError: "Sarwii Waɓɓi",
    demoOrderNote: "Nde misaale.",
    totalAmount: "Timmol",
    transactionFee: "Ñamiri Bambeh (1%)",
    grandTotal: "Timmol Fof",

    sellProduce: "Naattin Liɓɓi Maa",
    step1: "Haala Liɓɓi",
    step2: "Nokku & Janngirde",
    step3: "Sawruuje & Ƴeewtaare",
    productName: "Innde Liɓɓi",
    category: "Daaci",
    pricePerUnit: "Njamndi (FCFA)",
    unitLabel: "Wondirde",
    isOrganic: "Liɓɓi daano",
    availableForDelivery: "Waawi artirde",
    description: "Janngirde",
    descriptionPlaceholder: "Janngir daneeli…",
    locationLabel: "Nokku Maa",
    locationPlaceholder: "si'i. Bamenda, Nkwen",
    photos: "Sawruuje (faa 4)",
    addPhoto: "Natt Sawru",
    reviewListing: "Ƴeew & Neld",
    submitListing: "Natt Jayngel",
    listingSuccess: "Jayngel Danɗii!",
    listingSuccessSub: "Liɓɓi maa tawii njiimaaji.",
    saveDraft: "Dann Kabaaru",
    draftSaved: "Kabaaru dannii",
    photoError: "Ko JPG, PNG walla WebP, max 5 MB.",
    fillRequired: "Tiim fannu fof.",

    cartEmpty: "Sagas maa fotaani",
    continueShopping: "Jokku Sooding",
    checkout: "Ñammbu",
    subtotal: "Dow",
    fee1pct: "Ñamiri Bambeh (1%)",
    total: "Timmol",

    groupBuyingAd: {
      title: "Ƴoorgo Sooding — Dannee Fof",
      subtitle: "Naatir sarwiiji fewndo gonooɓe.",
      cta: "Naatir Ɗoo",
    } as any,
    sellProduceAd: {
      title: "A Winndiyanke?",
      subtitle: "Natt liɓɓi maa ko 3 minti.",
      cta: "Fuɗɗo Fiyude",
    } as any,
  },
};

/**
 * Translate a key for the given language.
 * For object-type keys (like groupBuyingAd), returns the object directly.
 * For function-type values (plurals), returns the function.
 */
export function t(key: string, lang: string): any {
  const dict = translations[lang] ?? translations["en"];
  const val = dict?.[key] ?? translations["en"]?.[key] ?? key;
  return val;
}
