// AUTO-GENERATED by .bambeh-ops/patch.ps1
import { NavigateFunction } from "react-router-dom";
export function requireAuth(isAuthenticated: boolean, navigate: NavigateFunction, redirectTo: string): boolean {
  if (!isAuthenticated) {
    navigate("/login?redirect=" + encodeURIComponent(redirectTo));
    return false;
  }
  return true;
}
