/**
 * src/context/LanguageContext.tsx — Bambeh Marketplace
 * ✅ Uses unified key: "Bambeh_language" (matches LanguageSelection.tsx)
 * ✅ Full translations: EN / FR / Pidgin / AR / FF (Fulfulde)
 * ✅ Covers: Navigation, FarmFresh, Jobs, Marketplace, Cart, Payment, Voice
 * © 2025–2026 BAMBEH SARL. All rights reserved.
 */

import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

// ─── Translation map ──────────────────────────────────────────────────────────
const translations: Record<string, Record<string, string>> = {
  en: {
    "tracking.loading": "Loading order details...",
    "tracking.loadError": "Unable to load order details. Please try again.",
    "tracking.notFound": "Order Not Found",
    "tracking.notFoundDesc": "We couldn't find that order. Please check the order ID and try again.",
    "tracking.tryAgain": "Try Again",
    "tracking.back": "Back",
    "tracking.refresh": "Refresh",
    "tracking.orderNumber": "Order Number",
    "tracking.deliveredOn": "Delivered On",
    "tracking.estDelivery": "Estimated Delivery",
    "tracking.datePending": "Pending",
    "tracking.timeline": "Tracking Timeline",
    "tracking.courierDetails": "Courier Details",
    "tracking.courier": "Courier",
    "tracking.trackingNumber": "Tracking Number",
    "tracking.copy": "Copy",
    "tracking.copied": "Copied!",
    "tracking.shippingAddress": "Shipping Address",
    "tracking.orderItems": "Order Items",
    "tracking.qty": "Qty:",
    "tracking.subtotal": "Subtotal",
    "tracking.shipping": "Shipping",
    "tracking.total": "Total",
    "tracking.paymentMethod": "Payment Method",
    "tracking.needHelp": "Need Help?",
    "tracking.chatSupport": "Chat Support",
    "tracking.orderHelp": "Order Help",
    "tracking.backToOrders": "Back to Orders",
    "tracking.continueShopping": "Continue Shopping",
    "tracking.status.pending": "Pending",
    "tracking.status.confirmed": "Confirmed",
    "orders.title": "My Orders",
    "orders.refresh": "Refresh orders",
    "orders.loading": "Loading your orders...",
    "orders.noneYet": "No orders yet",
    "orders.emptyDesc": "When you buy something on Bambeh, your orders will appear here.",
    "orders.browseMarketplace": "Browse Marketplace",
    "orders.orderNum": "Order #",
    "orders.track": "Track Order",
    "orders.status.inTransit": "In Transit",
    "orders.status.delivered": "Delivered",
    "orders.status.processing": "Processing",
    "orders.status.shipped": "Shipped",
    "orders.status.outForDelivery": "Out for Delivery",
    "orders.status.cancelled": "Cancelled",
    "settings.language": "Language",
    "common.logout": "Logout",
    "common.settings": "Settings",
    "nav.favorites": "Favorites",
    "nav.orders": "Orders",
    "nav.myListings": "My Listings",
    "fav.title": "Favorites",
    "fav.saved": "saved",
    "fav.loginSync": "Log in to sync your favorites across all devices.",
    "fav.login": "Log in",
    "fav.noneYet": "No favorites yet",
    "fav.noneCategory": "No {category} favorites",
    "fav.tapHeart": "Tap the heart on any listing, job, or produce to save it here.",
    "fav.browse": "Browse",
    "fav.savedOn": "Saved",
    "fav.tabAll": "All",
    "fav.tabItems": "Items",
    "fav.tabFarm": "Farm",
    "fav.tabDeals": "Deals",
    "fav.typeItem": "Item",
    "fav.typeFlashDeal": "Flash Deal",
    "fav.typeGroupDeal": "Group Deal",
    "fav.typeFarmFresh": "Farm Fresh",
    "nav.jobs": "Jobs",
    "nav.marketplace": "Marketplace",
    "nav.services": "Services",
    "nav.rentals": "Rentals",
    "nav.vehicles": "Vehicles",
    "nav.exchange": "Exchange",
    "auth.brandingStrip": "Bambeh Marketplace \u2014 The Pulse of African Commerce",
    "footer.aboutTitle": "About Bambeh",
    "footer.aboutDesc": "Bambeh is the pulse of African commerce. Buy, sell, find jobs, rent, and connect across Cameroon and beyond.",
    "footer.aboutUs": "About Us",
    "footer.allRightsReserved": "All rights reserved.",
    "footer.categoriesTitle": "Categories",
    "footer.collapseFooter": "Collapse footer",
    "footer.collapseLabel": "Hide",
    "footer.companyTitle": "Company",
    "footer.contact": "Contact",
    "footer.contactSupport": "Contact Support",
    "footer.donate": "Donate",
    "footer.expandFooter": "Expand footer",
    "footer.expandLabel": "Show",
    "footer.helpCentre": "Help Centre",
    "footer.operatedBy": "Operated by",
    "footer.privacy": "Privacy",
    "footer.safetySecurity": "Safety & Security",
    "footer.subscriptionPlans": "Subscription Plans",
    "footer.subscriptions": "Subscriptions",
    "footer.supportBambeh": "Support Bambeh",
    "footer.supportTitle": "Support",
    "footer.terms": "Terms",
    "footer.transactionFeeBadge": "Only 1% Transaction Fee \u2014 Lowest in Any Marketplace!",
    "footer.viewCompanyProfile": "View Company Profile",
    // ── Navigation ───────────────────────────────────────────────────────────
    home: "Home",
    jobs: "Jobs",
    marketplace: "Marketplace",
    services: "Services",
    rentals: "Rentals",
    vehicles: "Vehicles",
    exchange: "Exchange",
    community: "Community",
    sell: "Sell",
    buy: "Buy",
    search: "Search",
    login: "Login",
    register: "Register",
    logout: "Logout",
    settings: "Settings",
    favorites: "Favorites",
    orders: "Orders",
    next: "Next",
    submit: "Submit",
    back: "Back",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    loading: "Loading…",
    error: "Something went wrong. Please try again.",
    retry: "Retry",
    seeAll: "See all",
    tryAgain: "Try Again",
    share: "Share",
    copyLink: "Link copied!",

    // ── Jobs page ─────────────────────────────────────────────────────────────
    jobsTitle: "Find Jobs 💼",
    postJob: "+ Post Job",
    jobSearchPlaceholder: "Search jobs or companies…",
    jobsLoading: "Loading jobs from Bambeh…",
    opportunities: "opportunities across Cameroon",
    filters: "Filters",
    mostRecent: "Most Recent",
    clearFilters: "✕ Clear all filters",
    jobType: "Job Type",
    region: "Region",
    jobsFound: "jobs found",
    newestFirst: "newest first",
    refresh: "↻ Refresh",
    noJobs: "No jobs posted yet",
    noJobsHint: "Be the first to post a job opportunity!",
    noMatch: "No jobs match your filters",
    clearAll: "Clear all filters",
    applyNow: "🚀 Apply Now",
    views: "views",
    negotiable: "Negotiable",
    salaryNotSpec: "Salary not specified",
    deadline: "Deadline",
    remote: "Remote",
    jobError: "Could not load jobs. Check your connection.",
    salary: "Monthly Salary",

    // ── Jobs category page ────────────────────────────────────────────────────
    allJobs: "All Jobs",
    opportunity: "opportunity",
    opportunitiesPlural: "opportunities",
    noJobsCategory: "No jobs posted yet",
    checkBack: "Check back soon or post one yourself!",
    viewApply: "View & Apply →",
    loadMore: "Load More Jobs",
    closed: "⛔ Closed — Deadline passed",
    closingSoon: "⏰ Closing soon",
    today: "Today!",
    dLeft: "d left",

    // ── Job detail page ───────────────────────────────────────────────────────
    jobNotFound: "Job not found",
    jobLoading: "Loading job details…",
    jobDescription: "Job Description",
    requirements: "Requirements & Skills",
    benefits: "Benefits & Perks",
    jobApplyNow: "Apply Now",
    applyWhatsApp: "Apply via WhatsApp",
    applyCall: "Call to Apply",
    applyEmail: "Apply via Email",
    applied: "Application Sent ✓",
    applying: "Sending application…",
    alreadyApplied: "You already applied for this job",
    expired: "This job has expired",
    deadline2: "Application deadline",
    candidates: "applicants",
    views2: "views",
    published: "Published",
    saved: "Saved",
    unsaved: "Bookmark",
    loginToApply: "Log in to apply",

    // ── Post job page ─────────────────────────────────────────────────────────
    postJobTitle: "Post a Job",
    postJobSubtitle: "Find the right talent across Cameroon",
    jobTitle: "Job Title *",
    jobTitlePh: "e.g. Senior Software Engineer",
    company: "Company / Organisation",
    companyPh: "Name of your company",
    jobCategory: "Job Category *",
    employmentType: "Employment Type *",
    experienceLevel: "Experience Level *",
    cityLocation: "City / Location *",
    cityPh: "e.g. Douala, Yaoundé…",
    regionLabel: "Region",
    isRemote: "Remote work available",
    salaryMin: "Min Salary (FCFA/month)",
    salaryMax: "Max Salary (FCFA/month)",
    salaryPh: "e.g. 150000",
    salaryNegotiable: "Salary is negotiable",
    applicationDeadline: "Application Deadline",
    jobDescription2: "Job Description *",
    jobDescPh: "Describe the role, responsibilities, and what a typical day looks like…",
    requirementsPh: "List qualifications, skills, and experience required…",
    benefitsLabel: "Benefits & Perks",
    benefitsPh: "Health insurance, transport allowance, bonuses…",
    tagsLabel: "Skills / Tags (comma separated)",
    tagsPh: "React, Node.js, Marketing, Excel…",
    howApply: "How should candidates apply?",
    applyInApp: "📱 Through Bambeh Platform",
    applyWhatsAppOpt: "💬 WhatsApp",
    applyCallOpt: "📞 Phone Call",
    applyEmailOpt: "📧 Email",
    applyContactPh: "Enter phone number or email for applications",
    publishing: "Publishing your job…",
    jobPosted: "Job posted successfully!",
    publishJob: "Publish Job",
    fillRequired: "Please fill all required fields (*)",
    loginRequired: "You must be logged in to post a job",
    companyLogoLabel: "Company Logo",
    chooseImage: "Choose image",

    // ── FarmFresh ─────────────────────────────────────────────────────────────
    farmFresh: "Farm Fresh",
    farmFreshSub: "Fresh produce direct from Cameroonian farmers",
    searchPlaceholder: "Search produce, location…",
    noProduceFound: "No produce found",
    noProduceFoundSub: "Try a different search or category, or be the first to list!",
    listYourProduce: "List Your Produce",
    showingSamples: "Showing sample listings",
    realListings: "listings available from local farmers",
    buyDirect: "Buy Direct From Farmers",
    buyDirectSub: "Fresh produce, fair prices, from farm to your table in Cameroon.",
    joinGroup: "Join Group Buy",
    organic: "Organic",
    noPhotoYet: "No photo yet",
    addToCart: "Add to Cart",
    added: "Added ✓",
    cart: "Cart",
    orderNow: "Order Now",
    quantity: "Qty",
    catAll: "All",
    catVegetables: "Vegetables",
    catFruits: "Fruits",
    catTubers: "Tubers",
    catGrains: "Grains",
    catLegumes: "Legumes",
    catHerbs: "Herbs",
    catDairy: "Dairy",
    aboutProduct: "About This Product",
    unit: "Unit",
    locationKey: "Location",
    deliveryKey: "Delivery",
    delivAvail: "Available",
    pickupOnly: "Pickup only",
    stockKey: "In Stock",
    yourFarmer: "Your Farmer",
    whatsappSeller: "WhatsApp Farmer",
    moreFarm: "More Farm Products",
    shareProduct: "Share This Product",
    shareWhatsApp: "Share on WhatsApp",
    freshnessGuarantee: "Freshness Guarantee",
    freshnessDesc: "If your produce arrives below standard, report within 24 hours and we'll arrange a replacement or full refund.",
    productNotFound: "Product Not Found",
    productNotFoundSub: "This product may be unavailable or has been removed.",
    backToFarmFresh: "Back to Farm Fresh",
    orderSummary: "Order Summary",
    deliveryAddress: "Delivery Address",
    deliveryAddressPlaceholder: "Quarter, street, landmark…",
    contactPhone: "Contact Phone",
    orderNotes: "Notes for Farmer (optional)",
    orderNotesPlaceholder: "Preferred delivery time, special instructions…",
    placeOrder: "Place Order",
    orderSuccess: "Order Placed!",
    orderSuccessSub: "The farmer will contact you shortly to confirm delivery.",
    orderError: "Order Failed",
    demoOrderNote: "This is a demo product. In production your order will be sent to a real farmer.",
    totalAmount: "Total",
    transactionFee: "Transaction Fee (1%)",
    grandTotal: "Grand Total",
    sellProduce: "List Your Produce",
    step1: "Produce Details",
    step2: "Location & Description",
    step3: "Photos & Review",
    productName: "Product Name",
    category: "Category",
    pricePerUnit: "Price per Unit (FCFA)",
    unitLabel: "Unit",
    isOrganic: "This produce is organic / naturally grown",
    availableForDelivery: "Available for delivery",
    description: "Description",
    descriptionPlaceholder: "Describe freshness, quality, harvest date…",
    locationLabel: "Your Location (Town / Quarter)",
    locationPlaceholder: "e.g. Bamenda, Nkwen Quarter",
    photos: "Photos (up to 4)",
    addPhoto: "Add Photo",
    reviewListing: "Review & Submit",
    submitListing: "Post Listing",
    listingSuccess: "Listing Published!",
    listingSuccessSub: "Your produce is now live. Buyers can see and order it.",
    saveDraft: "Save Draft",
    draftSaved: "Draft saved",
    photoError: "Only JPG, PNG or WebP, max 5 MB each.",
    fillRequired2: "Please fill in all required fields.",

    // ── Cart & Payment ────────────────────────────────────────────────────────
    cartEmpty: "Your cart is empty",
    cartEmptySub: "Browse listings and add items to your cart.",
    continueShopping: "Continue Shopping",
    checkout: "Checkout",
    removeItem: "Remove",
    subtotal: "Subtotal",
    fee1pct: "Bambeh Fee (1%)",
    total: "Total",
    payWithMoMo: "Pay with MTN MoMo",
    payWithOrange: "Pay with Orange Money",
    enterPhone: "Enter your mobile number",
    payNow: "Pay Now",
    paymentPending: "Payment Pending",
    paymentPendingSub: "Check your phone and approve the payment prompt.",
    paymentSuccess: "Payment Successful!",
    paymentFailed: "Payment Failed",
    paymentFailedSub: "Your payment was not completed. Please try again.",

    // ── Ad slots ──────────────────────────────────────────────────────────────
    groupBuyingAdTitle: "Group Buying — Save Together",
    groupBuyingAdSub: "Pool orders with neighbours and get better prices.",
    groupBuyingAdCta: "Join Now",
    sellProduceAdTitle: "Are You a Farmer?",
    sellProduceAdSub: "List your produce in 3 minutes and reach buyers across Cameroon.",
    sellProduceAdCta: "Start Selling",

    // ── Voice control ─────────────────────────────────────────────────────────
    voiceSearchFarmFresh: "Searching Farm Fresh for",
    voiceSearchJobs: "Searching Jobs for",
    voiceGoTo: "Going to",
    voiceNotFound: "I couldn't find that. Try saying a product name or page.",
  },

  fr: {
    "tracking.loading": "Chargement des détails de la commande...",
    "tracking.loadError": "Impossible de charger les détails de la commande. Veuillez réessayer.",
    "tracking.notFound": "Commande introuvable",
    "tracking.notFoundDesc": "Nous n'avons pas trouvé cette commande. Vérifiez le numéro de commande et réessayez.",
    "tracking.tryAgain": "Réessayer",
    "tracking.back": "Retour",
    "tracking.refresh": "Actualiser",
    "tracking.orderNumber": "Numéro de commande",
    "tracking.deliveredOn": "Livrée le",
    "tracking.estDelivery": "Livraison estimée",
    "tracking.datePending": "En attente",
    "tracking.timeline": "Suivi de la commande",
    "tracking.courierDetails": "Détails du transporteur",
    "tracking.courier": "Transporteur",
    "tracking.trackingNumber": "Numéro de suivi",
    "tracking.copy": "Copier",
    "tracking.copied": "Copié !",
    "tracking.shippingAddress": "Adresse de livraison",
    "tracking.orderItems": "Articles de la commande",
    "tracking.qty": "Qté :",
    "tracking.subtotal": "Sous-total",
    "tracking.shipping": "Livraison",
    "tracking.total": "Total",
    "tracking.paymentMethod": "Mode de paiement",
    "tracking.needHelp": "Besoin d'aide ?",
    "tracking.chatSupport": "Assistance par chat",
    "tracking.orderHelp": "Aide commande",
    "tracking.backToOrders": "Retour aux commandes",
    "tracking.continueShopping": "Continuer mes achats",
    "tracking.status.pending": "En attente",
    "tracking.status.confirmed": "Confirmée",
    "orders.title": "Mes commandes",
    "orders.refresh": "Actualiser les commandes",
    "orders.loading": "Chargement de vos commandes...",
    "orders.noneYet": "Aucune commande",
    "orders.emptyDesc": "Lorsque vous achetez quelque chose sur Bambeh, vos commandes apparaîtront ici.",
    "orders.browseMarketplace": "Parcourir le marché",
    "orders.orderNum": "Commande n° ",
    "orders.track": "Suivre la commande",
    "orders.status.inTransit": "En transit",
    "orders.status.delivered": "Livrée",
    "orders.status.processing": "En traitement",
    "orders.status.shipped": "Expédiée",
    "orders.status.outForDelivery": "En cours de livraison",
    "orders.status.cancelled": "Annulée",
    "settings.language": "Langue",
    "common.logout": "Déconnexion",
    "common.settings": "Paramètres",
    "nav.favorites": "Favoris",
    "nav.orders": "Commandes",
    "nav.myListings": "Mes annonces",
    "fav.title": "Favoris",
    "fav.saved": "enregistrés",
    "fav.loginSync": "Connectez-vous pour synchroniser vos favoris sur tous vos appareils.",
    "fav.login": "Se connecter",
    "fav.noneYet": "Aucun favori pour le moment",
    "fav.noneCategory": "Aucun favori {category}",
    "fav.tapHeart": "Touchez le cœur sur une annonce, un emploi ou un produit pour l'enregistrer ici.",
    "fav.browse": "Parcourir",
    "fav.savedOn": "Enregistré",
    "fav.tabAll": "Tous",
    "fav.tabItems": "Articles",
    "fav.tabFarm": "Ferme",
    "fav.tabDeals": "Offres",
    "fav.typeItem": "Article",
    "fav.typeFlashDeal": "Offre flash",
    "fav.typeGroupDeal": "Achat groupé",
    "fav.typeFarmFresh": "Ferme Fraîche",
    "nav.jobs": "Emplois",
    "nav.marketplace": "March\u00e9",
    "nav.services": "Services",
    "nav.rentals": "Locations",
    "nav.vehicles": "V\u00e9hicules",
    "nav.exchange": "\u00c9change",
    "auth.brandingStrip": "Bambeh Marketplace \u2014 Le pouls du commerce africain",
    "footer.aboutTitle": "\u00c0 propos de Bambeh",
    "footer.aboutDesc": "Bambeh est le pouls du commerce africain. Achetez, vendez, trouvez un emploi, louez et connectez-vous partout au Cameroun et au-del\u00e0.",
    "footer.aboutUs": "\u00c0 propos",
    "footer.allRightsReserved": "Tous droits r\u00e9serv\u00e9s.",
    "footer.categoriesTitle": "Cat\u00e9gories",
    "footer.collapseFooter": "R\u00e9duire le pied de page",
    "footer.collapseLabel": "Masquer",
    "footer.companyTitle": "Entreprise",
    "footer.contact": "Contact",
    "footer.contactSupport": "Contacter le support",
    "footer.donate": "Faire un don",
    "footer.expandFooter": "Afficher le pied de page",
    "footer.expandLabel": "Afficher",
    "footer.helpCentre": "Centre d'aide",
    "footer.operatedBy": "Exploit\u00e9 par",
    "footer.privacy": "Confidentialit\u00e9",
    "footer.safetySecurity": "S\u00e9curit\u00e9",
    "footer.subscriptionPlans": "Forfaits d'abonnement",
    "footer.subscriptions": "Abonnements",
    "footer.supportBambeh": "Soutenir Bambeh",
    "footer.supportTitle": "Assistance",
    "footer.terms": "Conditions",
    "footer.transactionFeeBadge": "Seulement 1% de frais \u2014 les plus bas du march\u00e9 !",
    "footer.viewCompanyProfile": "Voir le profil de l'entreprise",
    home: "Accueil",
    jobs: "Emplois",
    marketplace: "Marché",
    services: "Services",
    rentals: "Locations",
    vehicles: "Véhicules",
    exchange: "Échange",
    community: "Communauté",
    sell: "Vendre",
    buy: "Acheter",
    search: "Rechercher",
    login: "Connexion",
    register: "S'inscrire",
    logout: "Déconnexion",
    settings: "Paramètres",
    favorites: "Favoris",
    orders: "Commandes",
    next: "Suivant",
    submit: "Soumettre",
    back: "Retour",
    cancel: "Annuler",
    save: "Enregistrer",
    edit: "Modifier",
    delete: "Supprimer",
    confirm: "Confirmer",
    loading: "Chargement…",
    error: "Une erreur est survenue. Veuillez réessayer.",
    retry: "Réessayer",
    seeAll: "Voir tout",
    tryAgain: "Réessayer",
    share: "Partager",
    copyLink: "Lien copié !",

    jobsTitle: "Trouver un emploi 💼",
    postJob: "+ Publier une offre",
    jobSearchPlaceholder: "Rechercher emplois ou entreprises…",
    jobsLoading: "Chargement des offres…",
    opportunities: "opportunités au Cameroun",
    filters: "Filtres",
    mostRecent: "Plus récent",
    clearFilters: "✕ Effacer tous les filtres",
    jobType: "Type d'emploi",
    region: "Région",
    jobsFound: "offres trouvées",
    newestFirst: "plus récent d'abord",
    refresh: "↻ Actualiser",
    noJobs: "Aucune offre publiée",
    noJobsHint: "Soyez le premier à publier une offre !",
    noMatch: "Aucune offre ne correspond",
    clearAll: "Effacer les filtres",
    applyNow: "🚀 Postuler maintenant",
    views: "vues",
    negotiable: "Négociable",
    salaryNotSpec: "Salaire non précisé",
    deadline: "Date limite",
    remote: "Télétravail",
    jobError: "Impossible de charger les offres. Vérifiez votre connexion.",
    salary: "Salaire mensuel",

    allJobs: "Tous les emplois",
    opportunity: "opportunité",
    opportunitiesPlural: "opportunités",
    noJobsCategory: "Aucune offre publiée",
    checkBack: "Revenez bientôt ou publiez une offre !",
    viewApply: "Voir & Postuler →",
    loadMore: "Charger plus d'offres",
    closed: "⛔ Fermé — Délai dépassé",
    closingSoon: "⏰ Ferme bientôt",
    today: "Aujourd'hui !",
    dLeft: "j restants",

    jobNotFound: "Offre introuvable",
    jobLoading: "Chargement…",
    jobDescription: "Description du poste",
    requirements: "Exigences & Compétences",
    benefits: "Avantages",
    jobApplyNow: "Postuler maintenant",
    applyWhatsApp: "Postuler via WhatsApp",
    applyCall: "Appeler pour postuler",
    applyEmail: "Postuler par email",
    applied: "Candidature envoyée ✓",
    applying: "Envoi en cours…",
    alreadyApplied: "Vous avez déjà postulé",
    expired: "Cette offre a expiré",
    deadline2: "Date limite",
    candidates: "candidats",
    views2: "vues",
    published: "Publié le",
    saved: "Sauvegardé",
    unsaved: "Sauvegarder",
    loginToApply: "Connectez-vous pour postuler",

    postJobTitle: "Publier une offre",
    postJobSubtitle: "Trouvez les meilleurs talents au Cameroun",
    jobTitle: "Intitulé du poste *",
    jobTitlePh: "ex. Ingénieur logiciel senior",
    company: "Entreprise / Organisation",
    companyPh: "Nom de votre entreprise",
    jobCategory: "Catégorie *",
    employmentType: "Type de contrat *",
    experienceLevel: "Niveau d'expérience *",
    cityLocation: "Ville / Lieu *",
    cityPh: "ex. Douala, Yaoundé…",
    regionLabel: "Région",
    isRemote: "Télétravail possible",
    salaryMin: "Salaire min (FCFA/mois)",
    salaryMax: "Salaire max (FCFA/mois)",
    salaryPh: "ex. 150000",
    salaryNegotiable: "Salaire négociable",
    applicationDeadline: "Date limite de candidature",
    jobDescription2: "Description du poste *",
    jobDescPh: "Décrivez le poste, les responsabilités…",
    requirementsPh: "Qualifications, compétences requises…",
    benefitsLabel: "Avantages",
    benefitsPh: "Assurance maladie, transport, primes…",
    tagsLabel: "Compétences / Tags (virgule)",
    tagsPh: "React, Node.js, Marketing…",
    howApply: "Comment les candidats doivent-ils postuler ?",
    applyInApp: "📱 Via la plateforme Bambeh",
    applyWhatsAppOpt: "💬 WhatsApp",
    applyCallOpt: "📞 Appel téléphonique",
    applyEmailOpt: "📧 Email",
    applyContactPh: "Entrez le numéro ou email pour les candidatures",
    publishing: "Publication en cours…",
    jobPosted: "Offre publiée avec succès !",
    publishJob: "Publier l'offre",
    fillRequired: "Veuillez remplir tous les champs obligatoires (*)",
    loginRequired: "Vous devez être connecté pour publier une offre",
    companyLogoLabel: "Logo de l'entreprise",
    chooseImage: "Choisir une image",

    farmFresh: "Ferme Fraîche",
    farmFreshSub: "Produits frais directement des agriculteurs camerounais",
    searchPlaceholder: "Chercher un produit, une ville…",
    noProduceFound: "Aucun produit trouvé",
    noProduceFoundSub: "Essayez une autre recherche ou soyez le premier à publier !",
    listYourProduce: "Publier votre produit",
    showingSamples: "Exemples de produits",
    realListings: "produits disponibles d'agriculteurs locaux",
    buyDirect: "Achetez Directement aux Agriculteurs",
    buyDirectSub: "Produits frais, prix équitables, de la ferme à votre table.",
    joinGroup: "Rejoindre un groupe d'achat",
    organic: "Bio",
    noPhotoYet: "Pas de photo",
    addToCart: "Ajouter au panier",
    added: "Ajouté ✓",
    cart: "Panier",
    orderNow: "Commander",
    quantity: "Qté",
    catAll: "Tout",
    catVegetables: "Légumes",
    catFruits: "Fruits",
    catTubers: "Tubercules",
    catGrains: "Céréales",
    catLegumes: "Légumineuses",
    catHerbs: "Herbes",
    catDairy: "Produits laitiers",
    aboutProduct: "À propos du produit",
    unit: "Unité",
    locationKey: "Lieu",
    deliveryKey: "Livraison",
    delivAvail: "Disponible",
    pickupOnly: "Récupération uniquement",
    stockKey: "En stock",
    yourFarmer: "Votre Agriculteur",
    whatsappSeller: "WhatsApp Agriculteur",
    moreFarm: "Plus de produits agricoles",
    shareProduct: "Partager ce produit",
    shareWhatsApp: "Partager sur WhatsApp",
    freshnessGuarantee: "Garantie de fraîcheur",
    freshnessDesc: "Si vos produits arrivent en dessous de nos standards, signalez-le en 24 h et nous organiserons un remplacement ou un remboursement complet.",
    productNotFound: "Produit introuvable",
    productNotFoundSub: "Ce produit est peut-être indisponible ou supprimé.",
    backToFarmFresh: "Retour à Ferme Fraîche",
    orderSummary: "Récapitulatif de commande",
    deliveryAddress: "Adresse de livraison",
    deliveryAddressPlaceholder: "Quartier, rue, point de repère…",
    contactPhone: "Téléphone de contact",
    orderNotes: "Notes pour l'agriculteur (facultatif)",
    orderNotesPlaceholder: "Heure de livraison préférée, instructions…",
    placeOrder: "Passer la commande",
    orderSuccess: "Commande passée !",
    orderSuccessSub: "L'agriculteur vous contactera bientôt pour confirmer la livraison.",
    orderError: "Échec de la commande",
    demoOrderNote: "Ceci est un produit de démonstration.",
    totalAmount: "Total",
    transactionFee: "Frais Bambeh (1 %)",
    grandTotal: "Total général",
    sellProduce: "Publier votre produit",
    step1: "Détails du produit",
    step2: "Lieu & Description",
    step3: "Photos & Vérification",
    productName: "Nom du produit",
    category: "Catégorie",
    pricePerUnit: "Prix par unité (FCFA)",
    unitLabel: "Unité",
    isOrganic: "Ce produit est biologique / cultivé naturellement",
    availableForDelivery: "Disponible pour la livraison",
    description: "Description",
    descriptionPlaceholder: "Décrivez la fraîcheur, la qualité, la date de récolte…",
    locationLabel: "Votre lieu (Ville / Quartier)",
    locationPlaceholder: "ex. Bafoussam, Quartier Tamdja",
    photos: "Photos (jusqu'à 4)",
    addPhoto: "Ajouter une photo",
    reviewListing: "Vérifier et soumettre",
    submitListing: "Publier l'annonce",
    listingSuccess: "Annonce publiée !",
    listingSuccessSub: "Votre produit est maintenant visible.",
    saveDraft: "Sauvegarder le brouillon",
    draftSaved: "Brouillon sauvegardé",
    photoError: "Seulement JPG, PNG ou WebP, max 5 Mo chacun.",
    fillRequired2: "Veuillez remplir tous les champs obligatoires.",

    cartEmpty: "Votre panier est vide",
    cartEmptySub: "Parcourez les annonces et ajoutez des articles à votre panier.",
    continueShopping: "Continuer les achats",
    checkout: "Passer à la caisse",
    removeItem: "Retirer",
    subtotal: "Sous-total",
    fee1pct: "Frais Bambeh (1 %)",
    total: "Total",
    payWithMoMo: "Payer avec MTN MoMo",
    payWithOrange: "Payer avec Orange Money",
    enterPhone: "Entrez votre numéro de téléphone mobile",
    payNow: "Payer maintenant",
    paymentPending: "Paiement en attente",
    paymentPendingSub: "Vérifiez votre téléphone et approuvez la demande de paiement.",
    paymentSuccess: "Paiement réussi !",
    paymentFailed: "Paiement échoué",
    paymentFailedSub: "Votre paiement n'a pas abouti. Veuillez réessayer.",

    groupBuyingAdTitle: "Achat groupé — Économisez ensemble",
    groupBuyingAdSub: "Groupez vos commandes avec vos voisins pour de meilleurs prix.",
    groupBuyingAdCta: "Rejoindre",
    sellProduceAdTitle: "Vous êtes agriculteur ?",
    sellProduceAdSub: "Publiez vos produits en 3 minutes et atteignez les acheteurs partout au Cameroun.",
    sellProduceAdCta: "Commencer à vendre",

    voiceSearchFarmFresh: "Recherche dans Ferme Fraîche pour",
    voiceSearchJobs: "Recherche d'emplois pour",
    voiceGoTo: "Navigation vers",
    voiceNotFound: "Je n'ai pas trouvé cela. Essayez un nom de produit ou de page.",
  },

  pidgin: {
    "tracking.loading": "Dey load order details...",
    "tracking.loadError": "We no fit load the order details. Try again.",
    "tracking.notFound": "We no find the order",
    "tracking.notFoundDesc": "We no fit find that order. Check the order ID well, then try again.",
    "tracking.tryAgain": "Try Again",
    "tracking.back": "Go Back",
    "tracking.refresh": "Refresh",
    "tracking.orderNumber": "Order Number",
    "tracking.deliveredOn": "Dem deliver am for",
    "tracking.estDelivery": "When e go reach",
    "tracking.datePending": "E never ready",
    "tracking.timeline": "Order Progress",
    "tracking.courierDetails": "Courier Details",
    "tracking.courier": "Courier",
    "tracking.trackingNumber": "Tracking Number",
    "tracking.copy": "Copy",
    "tracking.copied": "Don copy!",
    "tracking.shippingAddress": "Delivery Address",
    "tracking.orderItems": "Order Items",
    "tracking.qty": "Qty:",
    "tracking.subtotal": "Subtotal",
    "tracking.shipping": "Delivery",
    "tracking.total": "Total",
    "tracking.paymentMethod": "How you pay",
    "tracking.needHelp": "You need help?",
    "tracking.chatSupport": "Chat Support",
    "tracking.orderHelp": "Order Help",
    "tracking.backToOrders": "Go back to Orders",
    "tracking.continueShopping": "Continue Shopping",
    "tracking.status.pending": "Dey wait",
    "tracking.status.confirmed": "Dem confirm am",
    "orders.title": "My Orders",
    "orders.refresh": "Refresh orders",
    "orders.loading": "Dey load your orders...",
    "orders.noneYet": "No order dey yet",
    "orders.emptyDesc": "When you buy something for Bambeh, your orders go show here.",
    "orders.browseMarketplace": "Check Marketplace",
    "orders.orderNum": "Order #",
    "orders.track": "Track Order",
    "orders.status.inTransit": "Dey for road",
    "orders.status.delivered": "Don deliver",
    "orders.status.processing": "Dey process",
    "orders.status.shipped": "Don ship",
    "orders.status.outForDelivery": "Dey come deliver",
    "orders.status.cancelled": "Dem cancel am",
    "settings.language": "Language",
    "common.logout": "Comot",
    "common.settings": "Settings",
    "nav.favorites": "Favorites",
    "nav.orders": "Orders",
    "nav.myListings": "My Listings",
    "fav.title": "Favorites",
    "fav.saved": "save",
    "fav.loginSync": "Login so your favorites fit follow you for all your devices.",
    "fav.login": "Login",
    "fav.noneYet": "No favorites yet",
    "fav.noneCategory": "No {category} favorites",
    "fav.tapHeart": "Press the heart for any listing, job or farm thing make e save here.",
    "fav.browse": "Look",
    "fav.savedOn": "Save",
    "fav.tabAll": "All",
    "fav.tabItems": "Items",
    "fav.tabFarm": "Farm",
    "fav.tabDeals": "Deals",
    "fav.typeItem": "Item",
    "fav.typeFlashDeal": "Flash Deal",
    "fav.typeGroupDeal": "Group Deal",
    "fav.typeFarmFresh": "Farm Fresh",
    "nav.jobs": "Jobs",
    "nav.marketplace": "Market",
    "nav.services": "Services",
    "nav.rentals": "Rentals",
    "nav.vehicles": "Vehicles",
    "nav.exchange": "Exchange",
    "auth.brandingStrip": "Bambeh Marketplace \u2014 The Heartbeat of African Business",
    "footer.aboutTitle": "About Bambeh",
    "footer.aboutDesc": "Bambeh na the heartbeat of African business. Buy, sell, find work, rent, and join people across Cameroon and beyond.",
    "footer.aboutUs": "About Us",
    "footer.allRightsReserved": "All rights reserved.",
    "footer.categoriesTitle": "Categories",
    "footer.collapseFooter": "Close footer",
    "footer.collapseLabel": "Hide",
    "footer.companyTitle": "Company",
    "footer.contact": "Contact",
    "footer.contactSupport": "Contact Support",
    "footer.donate": "Donate",
    "footer.expandFooter": "Open footer",
    "footer.expandLabel": "Show",
    "footer.helpCentre": "Help Center",
    "footer.operatedBy": "Dem dey run am by",
    "footer.privacy": "Privacy",
    "footer.safetySecurity": "Safety & Security",
    "footer.subscriptionPlans": "Subscription Plans",
    "footer.subscriptions": "Subscriptions",
    "footer.supportBambeh": "Support Bambeh",
    "footer.supportTitle": "Support",
    "footer.terms": "Terms",
    "footer.transactionFeeBadge": "Na 1% Transaction Fee \u2014 the lowest for any marketplace!",
    "footer.viewCompanyProfile": "See Company Profile",
    home: "Home",
    jobs: "Jobs",
    marketplace: "Market",
    services: "Services",
    rentals: "Rentals",
    vehicles: "Cars",
    exchange: "Exchange",
    community: "Community",
    sell: "Sell",
    buy: "Buy",
    search: "Search",
    login: "Login",
    register: "Register",
    logout: "Logout",
    settings: "Settings",
    favorites: "Favorites",
    orders: "Orders",
    next: "Next",
    submit: "Submit",
    back: "Back",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    loading: "E dey load…",
    error: "Something spoil. Try again.",
    retry: "Try Again",
    seeAll: "See all",
    tryAgain: "Try again",
    share: "Share",
    copyLink: "Link don copy!",

    jobsTitle: "Find Work 💼",
    postJob: "+ Post Work",
    jobSearchPlaceholder: "Search work or company…",
    jobsLoading: "Dem dey load work…",
    opportunities: "opportunities for Cameroon",
    filters: "Filter",
    mostRecent: "New new",
    clearFilters: "✕ Clear all filter",
    jobType: "Work Type",
    region: "Region",
    jobsFound: "work dey",
    newestFirst: "new ones first",
    refresh: "↻ Refresh",
    noJobs: "No work yet",
    noJobsHint: "You be the first to post work!",
    noMatch: "No work match your filter",
    clearAll: "Clear filter",
    applyNow: "🚀 Apply Now",
    views: "people see am",
    negotiable: "E fit negotiate",
    salaryNotSpec: "No salary talk",
    deadline: "Last date",
    remote: "Online work",
    jobError: "We no fit load work.",
    salary: "Month salary",

    allJobs: "All Work",
    opportunity: "opportunity",
    opportunitiesPlural: "opportunities",
    noJobsCategory: "No work yet",
    checkBack: "Come back later or post work!",
    viewApply: "See & Apply →",
    loadMore: "Load more work",
    closed: "⛔ E don close",
    closingSoon: "⏰ E go close soon",
    today: "Today!",
    dLeft: "days left",

    jobNotFound: "Work no dey",
    jobLoading: "Dey load…",
    jobDescription: "Work description",
    requirements: "Wetin dem need",
    benefits: "Bonus things",
    jobApplyNow: "Apply Now",
    applyWhatsApp: "Apply for WhatsApp",
    applyCall: "Call make apply",
    applyEmail: "Send email apply",
    applied: "You don apply ✓",
    applying: "Dey send am…",
    alreadyApplied: "You don apply before",
    expired: "Work don finish",
    deadline2: "Last date",
    candidates: "people apply",
    views2: "people see am",
    published: "Dem post am",
    saved: "You don save am",
    unsaved: "Save am",
    loginToApply: "Login first apply",

    postJobTitle: "Post Work",
    postJobSubtitle: "Find correct person for Cameroon",
    jobTitle: "Work Name *",
    jobTitlePh: "e.g. Big software engineer",
    company: "Company / Organisation",
    companyPh: "Your company name",
    jobCategory: "Work type *",
    employmentType: "Work arrangement *",
    experienceLevel: "Experience level *",
    cityLocation: "Town / Place *",
    cityPh: "e.g. Douala, Yaoundé…",
    regionLabel: "Region",
    isRemote: "Online work dey",
    salaryMin: "Small salary (FCFA/month)",
    salaryMax: "Big salary (FCFA/month)",
    salaryPh: "e.g. 150000",
    salaryNegotiable: "Salary e fit talk",
    applicationDeadline: "Last date to apply",
    jobDescription2: "Work description *",
    jobDescPh: "Tell us wetin the work be, wetin dem go do everyday…",
    requirementsPh: "List all the things dem need…",
    benefitsLabel: "Bonus things",
    benefitsPh: "Health, transport, bonus things…",
    tagsLabel: "Skills (separate with comma)",
    tagsPh: "React, Node.js, Marketing…",
    howApply: "How dem go apply?",
    applyInApp: "📱 Through Bambeh",
    applyWhatsAppOpt: "💬 WhatsApp",
    applyCallOpt: "📞 Phone call",
    applyEmailOpt: "📧 Email",
    applyContactPh: "Enter number or email",
    publishing: "Dey post your work…",
    jobPosted: "Your work don post!",
    publishJob: "Post the work",
    fillRequired: "Fill all * fields abeg",
    loginRequired: "You need login first",
    companyLogoLabel: "Company Logo",
    chooseImage: "Choose picture",

    farmFresh: "Farm Fresh",
    farmFreshSub: "Fresh tins direct from Cameroon farmers",
    searchPlaceholder: "Find food, place…",
    noProduceFound: "No food dey here",
    noProduceFoundSub: "Try different search or be first person post something!",
    listYourProduce: "List Your Tins",
    showingSamples: "Sample listings dey show",
    realListings: "listings dey from local farmers",
    buyDirect: "Buy Direct From Farmer",
    buyDirectSub: "Fresh food, good price, from farm reach your house.",
    joinGroup: "Join Group Buy",
    organic: "Organic",
    noPhotoYet: "No photo yet",
    addToCart: "Add for Cart",
    added: "E dey inside ✓",
    cart: "Cart",
    orderNow: "Order Now",
    quantity: "How Many",
    catAll: "All",
    catVegetables: "Vegetables",
    catFruits: "Fruits",
    catTubers: "Tubers",
    catGrains: "Grains",
    catLegumes: "Legumes",
    catHerbs: "Herbs",
    catDairy: "Dairy",
    aboutProduct: "About Dis Tin",
    unit: "Unit",
    locationKey: "Place",
    deliveryKey: "Delivery",
    delivAvail: "Dey available",
    pickupOnly: "Come take am",
    stockKey: "Quantity for hand",
    yourFarmer: "Your Farmer",
    whatsappSeller: "WhatsApp the Farmer",
    moreFarm: "More Farm Tins",
    shareProduct: "Share Dis Tin",
    shareWhatsApp: "Share for WhatsApp",
    freshnessGuarantee: "Freshness Guarantee",
    freshnessDesc: "If your food no fresh when e reach, report am for 24 hours, we go change am or give you back your money.",
    productNotFound: "Dis product no dey",
    productNotFoundSub: "E don remove or e no available again.",
    backToFarmFresh: "Back to Farm Fresh",
    orderSummary: "Order Summary",
    deliveryAddress: "Where dem go bring am",
    deliveryAddressPlaceholder: "Quarter, street, landmark…",
    contactPhone: "Your phone number",
    orderNotes: "Tell farmer something (optional)",
    orderNotesPlaceholder: "When you want am, special request…",
    placeOrder: "Place Order",
    orderSuccess: "Order Don Go!",
    orderSuccessSub: "Farmer go call you soon to confirm delivery.",
    orderError: "Order fail",
    demoOrderNote: "Na demo product dis one.",
    totalAmount: "Total",
    transactionFee: "Bambeh Fee (1%)",
    grandTotal: "Grand Total",
    sellProduce: "Post Your Produce",
    step1: "Product Details",
    step2: "Place & Description",
    step3: "Photos & Review",
    productName: "Product Name",
    category: "Category",
    pricePerUnit: "Price for one unit (FCFA)",
    unitLabel: "Unit",
    isOrganic: "Na organic / natural food",
    availableForDelivery: "You fit deliver am",
    description: "Description",
    descriptionPlaceholder: "Talk about how fresh, quality, when dem harvest am…",
    locationLabel: "Your Place (Town / Quarter)",
    locationPlaceholder: "e.g. Bamenda, Nkwen Quarter",
    photos: "Photos (up to 4)",
    addPhoto: "Add Photo",
    reviewListing: "Check and Submit",
    submitListing: "Post Am",
    listingSuccess: "Listing Done Post!",
    listingSuccessSub: "Your produce dey live. Buyers go see am.",
    saveDraft: "Save Draft",
    draftSaved: "Draft saved",
    photoError: "Only JPG, PNG or WebP, max 5 MB each.",
    fillRequired2: "Fill all the required fields abeg.",

    cartEmpty: "Your cart empty",
    cartEmptySub: "Browse and add tins for your cart.",
    continueShopping: "Continue Shopping",
    checkout: "Go Pay",
    removeItem: "Remove",
    subtotal: "Subtotal",
    fee1pct: "Bambeh Fee (1%)",
    total: "Total",
    payWithMoMo: "Pay with MTN MoMo",
    payWithOrange: "Pay with Orange Money",
    enterPhone: "Enter your phone number",
    payNow: "Pay Now",
    paymentPending: "Payment Pending",
    paymentPendingSub: "Check your phone, approve the payment.",
    paymentSuccess: "Payment Don Enter!",
    paymentFailed: "Payment Fail",
    paymentFailedSub: "Your payment no go through. Try again.",

    groupBuyingAdTitle: "Group Buy — Save Together",
    groupBuyingAdSub: "Pool orders with your people for better prices.",
    groupBuyingAdCta: "Join Now",
    sellProduceAdTitle: "You be Farmer?",
    sellProduceAdSub: "Post your produce for 3 minutes, reach buyers all over Cameroon.",
    sellProduceAdCta: "Start Sell",

    voiceSearchFarmFresh: "Searching Farm Fresh for",
    voiceSearchJobs: "Searching Jobs for",
    voiceGoTo: "Going to",
    voiceNotFound: "I no find am. Try product name or page name.",
  },

  ar: {
    "tracking.loading": "جارٍ تحميل تفاصيل الطلب...",
    "tracking.loadError": "تعذّر تحميل تفاصيل الطلب. يرجى المحاولة مرة أخرى.",
    "tracking.notFound": "الطلب غير موجود",
    "tracking.notFoundDesc": "لم نتمكن من العثور على هذا الطلب. تحقّق من رقم الطلب وحاول مرة أخرى.",
    "tracking.tryAgain": "حاول مرة أخرى",
    "tracking.back": "رجوع",
    "tracking.refresh": "تحديث",
    "tracking.orderNumber": "رقم الطلب",
    "tracking.deliveredOn": "تم التوصيل في",
    "tracking.estDelivery": "موعد التوصيل المتوقع",
    "tracking.datePending": "قيد الانتظار",
    "tracking.timeline": "تتبّع الطلب",
    "tracking.courierDetails": "تفاصيل شركة التوصيل",
    "tracking.courier": "شركة التوصيل",
    "tracking.trackingNumber": "رقم التتبّع",
    "tracking.copy": "نسخ",
    "tracking.copied": "تم النسخ!",
    "tracking.shippingAddress": "عنوان التوصيل",
    "tracking.orderItems": "عناصر الطلب",
    "tracking.qty": "الكمية:",
    "tracking.subtotal": "المجموع الفرعي",
    "tracking.shipping": "التوصيل",
    "tracking.total": "الإجمالي",
    "tracking.paymentMethod": "طريقة الدفع",
    "tracking.needHelp": "تحتاج مساعدة؟",
    "tracking.chatSupport": "الدعم عبر المحادثة",
    "tracking.orderHelp": "مساعدة الطلب",
    "tracking.backToOrders": "العودة إلى الطلبات",
    "tracking.continueShopping": "متابعة التسوّق",
    "tracking.status.pending": "قيد الانتظار",
    "tracking.status.confirmed": "مؤكَّد",
    "orders.title": "طلباتي",
    "orders.refresh": "تحديث الطلبات",
    "orders.loading": "جارٍ تحميل طلباتك...",
    "orders.noneYet": "لا توجد طلبات بعد",
    "orders.emptyDesc": "عند شرائك شيئًا على بامبيه، ستظهر طلباتك هنا.",
    "orders.browseMarketplace": "تصفّح السوق",
    "orders.orderNum": "طلب رقم ",
    "orders.track": "تتبّع الطلب",
    "orders.status.inTransit": "في الطريق",
    "orders.status.delivered": "تم التوصيل",
    "orders.status.processing": "جاري المعالجة",
    "orders.status.shipped": "تم الشحن",
    "orders.status.outForDelivery": "خرج للتوصيل",
    "orders.status.cancelled": "مُلغى",
    "settings.language": "اللغة",
    "common.logout": "تسجيل الخروج",
    "common.settings": "الإعدادات",
    "nav.favorites": "المفضلة",
    "nav.orders": "الطلبات",
    "nav.myListings": "إعلاناتي",
    "fav.title": "المفضلة",
    "fav.saved": "تم حفظها",
    "fav.loginSync": "تسجيل الدخول لمزامنة مفضلاتك عبر جميع الأجهزة.",
    "fav.login": "تسجيل الدخول",
    "fav.noneYet": "لا توجد مفضلات بعد",
    "fav.noneCategory": "لا توجد مفضلات في فئة {category}",
    "fav.tapHeart": "اضغط على القلب في أي إعلان أو وظيفة أو منتج لحفظه هنا.",
    "fav.browse": "تصفّح",
    "fav.savedOn": "تم الحفظ",
    "fav.tabAll": "الكل",
    "fav.tabItems": "العناصر",
    "fav.tabFarm": "المزرعة",
    "fav.tabDeals": "العروض",
    "fav.typeItem": "عنصر",
    "fav.typeFlashDeal": "عرض سريع",
    "fav.typeGroupDeal": "عرض جماعي",
    "fav.typeFarmFresh": "طازج من المزرعة",
    "footer.operatedBy": "مُدار بواسطة",
    "footer.collapseLabel": "إخفاء",
    "footer.expandLabel": "إظهار",
    "footer.aboutDesc": "بامبيه هو نبض التجارة الأفريقية. اشترِ، وبع، وابحث عن وظائف، واستأجر، وتواصل في جميع أنحاء الكاميرون وخارجها.",
    "footer.aboutUs": "معلومات عنا",
    "footer.allRightsReserved": "جميع الحقوق محفوظة",
    "footer.contact": "اتصل بنا",
    "footer.contactSupport": "الاتصال بالدعم",
    "footer.donate": "تبرع",
    "footer.helpCentre": "مركز المساعدة",
    "footer.privacy": "الخصوصية",
    "footer.safetySecurity": "الأمان والحماية",
    "footer.subscriptionPlans": "خطط الاشتراك",
    "footer.subscriptions": "الاشتراكات",
    "footer.supportBambeh": "دعم بامبيه",
    "footer.terms": "الشروط",
    "footer.transactionFeeBadge": "رسوم معاملات 1% فقط — الأقل في أي سوق",
    "footer.viewCompanyProfile": "عرض ملف الشركة",
    "nav.jobs": "الوظائف",
    "nav.marketplace": "السوق",
    "nav.services": "الخدمات",
    "nav.rentals": "الإيجارات",
    "nav.vehicles": "المركبات",
    "nav.exchange": "تبادل",
    "footer.aboutTitle": "\u0639\u0646 \u0628\u0627\u0645\u0628\u064a\u0647",
    "footer.categoriesTitle": "\u0627\u0644\u0641\u0626\u0627\u062a",
    "footer.supportTitle": "\u0627\u0644\u062f\u0639\u0645",
    "footer.companyTitle": "\u0627\u0644\u0634\u0631\u0643\u0629",
    home: "الرئيسية",
    jobs: "الوظائف",
    marketplace: "السوق",
    services: "الخدمات",
    rentals: "الإيجارات",
    vehicles: "المركبات",
    exchange: "التبادل",
    community: "المجتمع",
    sell: "بيع",
    buy: "شراء",
    search: "بحث",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    settings: "الإعدادات",
    favorites: "المفضلة",
    orders: "الطلبات",
    next: "التالي",
    submit: "إرسال",
    back: "رجوع",
    cancel: "إلغاء",
    save: "حفظ",
    edit: "تعديل",
    delete: "حذف",
    confirm: "تأكيد",
    loading: "جارٍ التحميل…",
    error: "حدث خطأ. يرجى المحاولة مجدداً.",
    retry: "إعادة المحاولة",
    seeAll: "عرض الكل",
    tryAgain: "حاول مرة أخرى",
    share: "مشاركة",
    copyLink: "تم نسخ الرابط!",

    jobsTitle: "البحث عن عمل 💼",
    postJob: "+ نشر وظيفة",
    jobSearchPlaceholder: "البحث عن وظائف أو شركات…",
    jobsLoading: "جارٍ تحميل الوظائف…",
    opportunities: "فرصة عمل في الكاميرون",
    filters: "تصفية",
    mostRecent: "الأحدث",
    clearFilters: "✕ مسح جميع التصفيات",
    jobType: "نوع الوظيفة",
    region: "المنطقة",
    jobsFound: "وظيفة موجودة",
    newestFirst: "الأحدث أولاً",
    refresh: "↻ تحديث",
    noJobs: "لا توجد وظائف بعد",
    noJobsHint: "كن أول من ينشر فرصة عمل!",
    noMatch: "لا توجد وظائف مطابقة",
    clearAll: "مسح الكل",
    applyNow: "🚀 تقدم الآن",
    views: "مشاهدة",
    negotiable: "قابل للتفاوض",
    salaryNotSpec: "الراتب غير محدد",
    deadline: "آخر موعد",
    remote: "عن بُعد",
    jobError: "تعذر تحميل الوظائف.",
    salary: "الراتب الشهري",

    allJobs: "جميع الوظائف",
    opportunity: "فرصة",
    opportunitiesPlural: "فرص",
    noJobsCategory: "لا توجد وظائف بعد",
    checkBack: "عد قريباً أو انشر وظيفة!",
    viewApply: "عرض وتقديم →",
    loadMore: "تحميل المزيد",
    closed: "⛔ مغلق — انتهى الموعد",
    closingSoon: "⏰ ينتهي قريباً",
    today: "اليوم!",
    dLeft: "أيام متبقية",

    jobNotFound: "الوظيفة غير موجودة",
    jobLoading: "جارٍ التحميل…",
    jobDescription: "وصف الوظيفة",
    requirements: "المتطلبات والمهارات",
    benefits: "المزايا والمكافآت",
    jobApplyNow: "تقدم الآن",
    applyWhatsApp: "التقديم عبر واتساب",
    applyCall: "اتصل للتقديم",
    applyEmail: "التقديم بالبريد الإلكتروني",
    applied: "تم إرسال الطلب ✓",
    applying: "جارٍ الإرسال…",
    alreadyApplied: "لقد تقدمت بالفعل",
    expired: "انتهت صلاحية الوظيفة",
    deadline2: "آخر موعد",
    candidates: "متقدم",
    views2: "مشاهدة",
    published: "نُشر في",
    saved: "محفوظ",
    unsaved: "حفظ",
    loginToApply: "سجّل دخولك للتقديم",

    postJobTitle: "نشر وظيفة",
    postJobSubtitle: "اعثر على المواهب في الكاميرون",
    jobTitle: "المسمى الوظيفي *",
    jobTitlePh: "مثل: مهندس برمجيات أول",
    company: "الشركة / المؤسسة",
    companyPh: "اسم شركتك",
    jobCategory: "الفئة *",
    employmentType: "نوع التوظيف *",
    experienceLevel: "مستوى الخبرة *",
    cityLocation: "المدينة / الموقع *",
    cityPh: "مثل: دوالا، ياوندي…",
    regionLabel: "المنطقة",
    isRemote: "يتوفر عمل عن بُعد",
    salaryMin: "الحد الأدنى للراتب (فرنك/شهر)",
    salaryMax: "الحد الأقصى للراتب",
    salaryPh: "مثل: 150000",
    salaryNegotiable: "الراتب قابل للتفاوض",
    applicationDeadline: "آخر موعد للتقديم",
    jobDescription2: "وصف الوظيفة *",
    jobDescPh: "اوصف الدور والمسؤوليات…",
    requirementsPh: "اذكر المؤهلات والمهارات المطلوبة…",
    benefitsLabel: "المزايا والمكافآت",
    benefitsPh: "تأمين صحي، بدل نقل، مكافآت…",
    tagsLabel: "المهارات / الوسوم",
    tagsPh: "React, Node.js, تسويق…",
    howApply: "كيف يتقدم المرشحون؟",
    applyInApp: "📱 عبر منصة بامبيه",
    applyWhatsAppOpt: "💬 واتساب",
    applyCallOpt: "📞 مكالمة هاتفية",
    applyEmailOpt: "📧 البريد الإلكتروني",
    applyContactPh: "أدخل الرقم أو البريد الإلكتروني",
    publishing: "جارٍ النشر…",
    jobPosted: "تم نشر الوظيفة بنجاح!",
    publishJob: "نشر الوظيفة",
    fillRequired: "يرجى ملء جميع الحقول المطلوبة (*)",
    loginRequired: "يجب تسجيل الدخول لنشر وظيفة",
    companyLogoLabel: "شعار الشركة",
    chooseImage: "اختر صورة",

    farmFresh: "منتجات الحقل الطازجة",
    farmFreshSub: "منتجات طازجة مباشرة من مزارعي الكاميرون",
    searchPlaceholder: "ابحث عن منتج أو موقع…",
    noProduceFound: "لا توجد منتجات",
    noProduceFoundSub: "جرّب بحثاً آخر أو كن أول من ينشر!",
    listYourProduce: "أضف منتجك",
    showingSamples: "عرض نماذج المنتجات",
    realListings: "منتجات متاحة من المزارعين المحليين",
    buyDirect: "اشترِ مباشرة من المزارع",
    buyDirectSub: "منتجات طازجة وأسعار عادلة من المزرعة إلى مائدتك.",
    joinGroup: "انضم للشراء الجماعي",
    organic: "عضوي",
    noPhotoYet: "لا توجد صورة",
    addToCart: "أضف إلى السلة",
    added: "تمت الإضافة ✓",
    cart: "السلة",
    orderNow: "اطلب الآن",
    quantity: "الكمية",
    catAll: "الكل",
    catVegetables: "خضروات",
    catFruits: "فواكه",
    catTubers: "درنات",
    catGrains: "حبوب",
    catLegumes: "بقوليات",
    catHerbs: "أعشاب",
    catDairy: "منتجات الألبان",
    aboutProduct: "حول هذا المنتج",
    unit: "الوحدة",
    locationKey: "الموقع",
    deliveryKey: "التوصيل",
    delivAvail: "متاح",
    pickupOnly: "الاستلام الشخصي فقط",
    stockKey: "المخزون",
    yourFarmer: "مزارعك",
    whatsappSeller: "تواصل مع المزارع عبر واتساب",
    moreFarm: "مزيد من المنتجات الزراعية",
    shareProduct: "مشاركة هذا المنتج",
    shareWhatsApp: "مشاركة على واتساب",
    freshnessGuarantee: "ضمان النضارة",
    freshnessDesc: "إذا وصلت منتجاتك دون المستوى، أبلغ عن ذلك خلال 24 ساعة وسنرتب استبداله أو استرداد المبلغ كاملاً.",
    productNotFound: "المنتج غير موجود",
    productNotFoundSub: "قد يكون هذا المنتج غير متاح أو تم حذفه.",
    backToFarmFresh: "العودة إلى منتجات الحقل",
    orderSummary: "ملخص الطلب",
    deliveryAddress: "عنوان التوصيل",
    deliveryAddressPlaceholder: "الحي، الشارع، معلم قريب…",
    contactPhone: "رقم الهاتف للتواصل",
    orderNotes: "ملاحظات للمزارع (اختياري)",
    orderNotesPlaceholder: "وقت التسليم المفضل، تعليمات خاصة…",
    placeOrder: "تأكيد الطلب",
    orderSuccess: "تم تقديم الطلب!",
    orderSuccessSub: "سيتواصل معك المزارع قريباً لتأكيد التوصيل.",
    orderError: "فشل تقديم الطلب",
    demoOrderNote: "هذا منتج تجريبي.",
    totalAmount: "الإجمالي",
    transactionFee: "رسوم بامبيه (1٪)",
    grandTotal: "الإجمالي الكلي",
    sellProduce: "أضف منتجك",
    step1: "تفاصيل المنتج",
    step2: "الموقع والوصف",
    step3: "الصور والمراجعة",
    productName: "اسم المنتج",
    category: "الفئة",
    pricePerUnit: "السعر لكل وحدة (FCFA)",
    unitLabel: "الوحدة",
    isOrganic: "هذا المنتج عضوي / مزروع طبيعياً",
    availableForDelivery: "متاح للتوصيل",
    description: "الوصف",
    descriptionPlaceholder: "صف الجودة وتاريخ الحصاد وطريقة الزراعة…",
    locationLabel: "موقعك (المدينة / الحي)",
    locationPlaceholder: "مثال: ياوندي، حي الجامعة",
    photos: "الصور (حتى 4)",
    addPhoto: "إضافة صورة",
    reviewListing: "مراجعة وإرسال",
    submitListing: "نشر الإعلان",
    listingSuccess: "تم نشر الإعلان!",
    listingSuccessSub: "منتجك الآن ظاهر للمشترين.",
    saveDraft: "حفظ المسودة",
    draftSaved: "تم حفظ المسودة",
    photoError: "يُسمح فقط بصور JPG أو PNG أو WebP، بحد أقصى 5 ميغابايت.",
    fillRequired2: "يرجى ملء جميع الحقول المطلوبة.",

    cartEmpty: "سلتك فارغة",
    cartEmptySub: "تصفح الإعلانات وأضف ما تريد إلى سلتك.",
    continueShopping: "متابعة التسوق",
    checkout: "إتمام الشراء",
    removeItem: "إزالة",
    subtotal: "المجموع الجزئي",
    fee1pct: "رسوم بامبيه (1٪)",
    total: "الإجمالي",
    payWithMoMo: "الدفع عبر MTN MoMo",
    payWithOrange: "الدفع عبر Orange Money",
    enterPhone: "أدخل رقم هاتفك المحمول",
    payNow: "ادفع الآن",
    paymentPending: "في انتظار الدفع",
    paymentPendingSub: "تحقق من هاتفك وأقرّ طلب الدفع.",
    paymentSuccess: "تم الدفع بنجاح!",
    paymentFailed: "فشل الدفع",
    paymentFailedSub: "لم يكتمل دفعك. يرجى المحاولة مجدداً.",

    groupBuyingAdTitle: "الشراء الجماعي — وفّروا معاً",
    groupBuyingAdSub: "جمّعوا طلباتكم مع الجيران للحصول على أسعار أفضل.",
    groupBuyingAdCta: "انضم الآن",
    sellProduceAdTitle: "هل أنت مزارع؟",
    sellProduceAdSub: "أضف منتجاتك في 3 دقائق وصل إلى المشترين في الكاميرون.",
    sellProduceAdCta: "ابدأ البيع",

    voiceSearchFarmFresh: "البحث في منتجات الحقل عن",
    voiceSearchJobs: "البحث في الوظائف عن",
    voiceGoTo: "الانتقال إلى",
    voiceNotFound: "لم أتمكن من العثور على ذلك. جرّب اسم منتج أو صفحة.",
  },

  ff: {
    "tracking.loading": "Ɗon loowee fiɓindeeji umroore...",
    "tracking.loadError": "Hawri loowde fiɓindeeji umroore. Tiiɗno eto kadi.",
    "tracking.notFound": "Umroore yiyaaka",
    "tracking.notFoundDesc": "Min njiyaali umroore nden. Ƴeewu lambde umroore ndee, tiiɗno eto kadi.",
    "tracking.tryAgain": "Eto kadi",
    "tracking.back": "Rutto",
    "tracking.refresh": "Hesɗitin",
    "tracking.orderNumber": "Lambde umroore",
    "tracking.deliveredOn": "Yottinaama e",
    "tracking.estDelivery": "Sahaa yottingo faandaango",
    "tracking.datePending": "Ina habdi",
    "tracking.timeline": "Ɗowndagol umroore",
    "tracking.courierDetails": "Fiɓindeeji neldoowo",
    "tracking.courier": "Neldoowo",
    "tracking.trackingNumber": "Lambde ɗowndagol",
    "tracking.copy": "Natto",
    "tracking.copied": "Nattaama!",
    "tracking.shippingAddress": "Ñiiɓirde neldugo",
    "tracking.orderItems": "Kuuje umroore",
    "tracking.qty": "Keewal:",
    "tracking.subtotal": "Hawtaande les",
    "tracking.shipping": "Neldugo",
    "tracking.total": "Hawtaande fof",
    "tracking.paymentMethod": "Noone yoɓdi",
    "tracking.needHelp": "A soklii ballal?",
    "tracking.chatSupport": "Ballal e jokkondiral",
    "tracking.orderHelp": "Ballal umroore",
    "tracking.backToOrders": "Rutto e umrooje",
    "tracking.continueShopping": "Jokku coodgu",
    "tracking.status.pending": "Ina habdi",
    "tracking.status.confirmed": "Tabitinaama",
    "orders.title": "Umrooje am",
    "orders.refresh": "Hesɗitin umrooje",
    "orders.loading": "Umrooje maa ɗon loowee...",
    "orders.noneYet": "Umrooje alaa tawon",
    "orders.emptyDesc": "Si a soodii huunde e Bambeh, umrooje maa ɗon ɓanngina ɗoo.",
    "orders.browseMarketplace": "Yiilo luumo",
    "orders.orderNum": "Umroore #",
    "orders.track": "Ɗawndo umroore",
    "orders.status.inTransit": "Ɗon haa laawol",
    "orders.status.delivered": "Yottinaama",
    "orders.status.processing": "Ɗon huda",
    "orders.status.shipped": "Burtinaama ngam neldungo",
    "orders.status.outForDelivery": "Wurtake ngam yottingo",
    "orders.status.cancelled": "Oftaama",
    "settings.language": "Ɗemngal",
    "common.logout": "Yaltude",
    "common.settings": "Teelte",
    "nav.favorites": "Cuɓaaɗi",
    "nav.orders": "Umrooje",
    "nav.myListings": "Ko njeeyetee am",
    "fav.title": "Cuɓaaɗi",
    "fav.saved": "resama",
    "fav.loginSync": "Nastu ngam hawritingo cuɓaaɗi ma haa masiinji ma fof.",
    "fav.login": "Nastu",
    "fav.noneYet": "Walaa cuɓaaɗi tawo",
    "fav.noneCategory": "Walaa cuɓaaɗi {category} tawo",
    "fav.tapHeart": "Meemu ɓernde man dow kuugal, yeeyre, koo ngesa ngam resugo ɗum ɗo.",
    "fav.browse": "Lartu",
    "fav.savedOn": "Resama",
    "fav.tabAll": "Fof",
    "fav.tabItems": "Kuuje",
    "fav.tabFarm": "Ngesa",
    "fav.tabDeals": "Sannje",
    "fav.typeItem": "Huunde",
    "fav.typeFlashDeal": "Narra jooni-jooni",
    "fav.typeGroupDeal": "Narra kawtal yimɓe",
    "fav.typeFarmFresh": "Ko hecci diga ngesa",
    "footer.operatedBy": "Huwtinaama ko haani e / Yiilaama ko haani e",
    "footer.collapseLabel": "Suwɗu",
    "footer.expandLabel": "Suttin",
    "footer.aboutDesc": "Bambeh woni ɓernde yeeyruki Afrik. Sood, yeey, ɗonca gollorɗe, lura cuuɗi, boo jokku yimɓe haa njaajeendi Kamerun e sella muudum.",
    "footer.aboutUs": "Haala ameen / Haar dow ameen",
    "footer.allRightsReserved": "Hakkeeji ɗon maru fof",
    "footer.contact": "Jokkondiral",
    "footer.contactSupport": "Jokku e Wallitaare",
    "footer.donate": "Dokkal / Hokke njoɓdi",
    "footer.helpCentre": "Hoɗo Ballal",
    "footer.privacy": "Sirri",
    "footer.safetySecurity": "Kisndam e Jam",
    "footer.subscriptionPlans": "Nooneji iiri njoɓdi",
    "footer.subscriptions": "Njoɓdi iiri gollal",
    "footer.supportBambeh": "Wallu Bambeh",
    "footer.terms": "Sariyaaji / Sarɗiiji",
    "footer.transactionFeeBadge": "Ko hebi njoɓdi teemedere ɗon reeta go'o (1%) - ɓuri les haa luumo kootoye",
    "footer.viewCompanyProfile": "Yeew kuugal kampani",
    "nav.jobs": "Gollorɗe",
    "nav.marketplace": "Luumo",
    "nav.services": "Kuugal / Sarwiisji",
    "nav.rentals": "Luraaji cuuɗi",
    "nav.vehicles": "Otooɓe / Mootaji",
    "nav.exchange": "Njaldinaare",
    "footer.aboutTitle": "Haar dow Bambeh / Habaru Bambeh",
    "footer.categoriesTitle": "Iiriiri / Nooneji",
    "footer.supportTitle": "Wallitaare / Ballal",
    "footer.companyTitle": "Kampani",
    home: "Jeyeendi",
    jobs: "Liggaade",
    marketplace: "Maare",
    services: "Ɓalɗe",
    rentals: "Hireeli",
    vehicles: "Ottooji",
    exchange: "Yoƴtaari",
    community: "Ɓiɓɓe",
    sell: "Fiyee",
    buy: "Soodee",
    search: "Ƴeewee",
    login: "Naatdee",
    register: "Restoree",
    logout: "Fuɗɗodee",
    settings: "Haɓɓitorde",
    favorites: "Faaɓaaɓe",
    orders: "Sarwiiji",
    next: "Ɓurngo",
    submit: "Neldee",
    back: "Heddii",
    cancel: "Haɗ",
    save: "Dannee",
    edit: "Rewindee",
    delete: "Siftoo",
    confirm: "Siftinee",
    loading: "E nder loodi…",
    error: "Huunde waɓɓi. Ɓettoo.",
    retry: "Ɓettoo",
    seeAll: "Hol fof",
    tryAgain: "Eɗɗoo yeeso",
    share: "Siiwtindiraa",
    copyLink: "Ñolndi jaɓɓaama!",

    jobsTitle: "Yiyde Golle 💼",
    postJob: "+ Fewtu Golle",
    jobSearchPlaceholder: "Yiylo golle walla liggey…",
    jobsLoading: "Nannginii golle…",
    opportunities: "golle e Kameruun",
    filters: "Tippitorɗe",
    mostRecent: "Ɓuuɓɗum",
    clearFilters: "✕ Huccit tippitorɗe fof",
    jobType: "Suudu Golle",
    region: "Leydi",
    jobsFound: "golle heɓtaama",
    newestFirst: "ɓuuɓɗum ɓoo",
    refresh: "↻ Heɓtu",
    noJobs: "Alaa golle fewti",
    noJobsHint: "Ardi fewtu golle!",
    noMatch: "Alaa golle faayi",
    clearAll: "Huccit tippitorɗe",
    applyNow: "🚀 Dañ Golle",
    views: "yiylaama",
    negotiable: "Naggi",
    salaryNotSpec: "Njobdi alaa",
    deadline: "Balɗe ɓennoo",
    remote: "E Ɓanndu",
    jobError: "Golle naataani.",
    salary: "Njobdi koorka",

    allJobs: "Golle fof",
    opportunity: "sago",
    opportunitiesPlural: "sagoji",
    noJobsCategory: "Alaa golle",
    checkBack: "Ardi tuma ɓee ko fewtu!",
    viewApply: "Yii & Dañ →",
    loadMore: "Nanngin Golleli",
    closed: "⛔ Uddii",
    closingSoon: "⏰ Ɓennoo seeɗa",
    today: "Hannde!",
    dLeft: "balɗe",

    jobNotFound: "Golle heɓaani",
    jobLoading: "Nannginii…",
    jobDescription: "Jaŋtugol Golle",
    requirements: "Ko heɓetee",
    benefits: "Nafaaji",
    jobApplyNow: "Dañ Golle",
    applyWhatsApp: "Jokkude e WhatsApp",
    applyCall: "Noddu ngam Dañde",
    applyEmail: "Imeel ngam Dañde",
    applied: "Jokkunde nootii ✓",
    applying: "Nannginii…",
    alreadyApplied: "Ko njimonaa yoodi",
    expired: "Golle ɓenni",
    deadline2: "Balɗe ɓennoo",
    candidates: "jokkooɓe",
    views2: "yiylaama",
    published: "Fewtiima",
    saved: "Adanaama",
    unsaved: "Adana",
    loginToApply: "Naatir ngam dañde",

    postJobTitle: "Fewtu Golle",
    postJobSubtitle: "Yiydaa ɗoo e Kameruun",
    jobTitle: "Innde Golle *",
    jobTitlePh: "taa. Injiniir ɓaleejo",
    company: "Liggey / Ƙulle",
    companyPh: "Innde liggey maa",
    jobCategory: "Suudu Golle *",
    employmentType: "Suudu Kontoraaji *",
    experienceLevel: "Karallaagal *",
    cityLocation: "Wuro / Ɓoggol *",
    cityPh: "taa. Douala, Yaoundé…",
    regionLabel: "Leydi",
    isRemote: "E Ɓanndu ɗon",
    salaryMin: "Njobdi bilahi (FCFA/koorka)",
    salaryMax: "Njobdi heeli (FCFA/koorka)",
    salaryPh: "taa. 150000",
    salaryNegotiable: "Njobdi naggi",
    applicationDeadline: "Balɗe ɓennoo",
    jobDescription2: "Jaŋtugol Golle *",
    jobDescPh: "Jaŋtu golle ndee, ko waɗɗataake…",
    requirementsPh: "Jaŋtu ko heɓetee, ɗemɗe, karallaagal…",
    benefitsLabel: "Nafaaji",
    benefitsPh: "Laamu cellal, njuɓɓudi, nafaaji…",
    tagsLabel: "Ɗemɗe (tippuɗe e tiindol)",
    tagsPh: "React, Node.js…",
    howApply: "No jokkorɗe poti jokkude?",
    applyInApp: "📱 E Bambeh",
    applyWhatsAppOpt: "💬 WhatsApp",
    applyCallOpt: "📞 Noddaare",
    applyEmailOpt: "📧 Imeel",
    applyContactPh: "Naatnu numeerol maa imeel",
    publishing: "Fewtinaama…",
    jobPosted: "Golle fewtiima!",
    publishJob: "Fewtu Golle",
    fillRequired: "Heɓtu goɗɗe fof peewnaaɗe (*)",
    loginRequired: "Naatir ngam fewtoyde golle",
    companyLogoLabel: "Sawru Liggey",
    chooseImage: "Soodii sawru",

    farmFresh: "Liɓɓi Ɗowi",
    farmFreshSub: "Liɓɓi daneeli fewndo winndiyanke Kamerun",
    searchPlaceholder: "Ƴeew liɓɓi, gure…",
    noProduceFound: "Liɓɓi alaa",
    noProduceFoundSub: "Ƴeew koɗum walla fuɗɗo jayngel!",
    listYourProduce: "Naattin Liɓɓi Maa",
    showingSamples: "Misaale liɓɓi",
    realListings: "liɓɓi daneeli winndiyankeeɓe",
    buyDirect: "Soodee Fewndo Winndiyanke",
    buyDirectSub: "Liɓɓi daneeli, njamndi yooɓii.",
    joinGroup: "Naatir Ƴoorgo",
    organic: "Daano",
    noPhotoYet: "Sawru alaa",
    addToCart: "Naattin Sagas",
    added: "E nder ✓",
    cart: "Sagas",
    orderNow: "Sarwii Ɗoo",
    quantity: "Timmol",
    catAll: "Fof",
    catVegetables: "Leɗɗe",
    catFruits: "Biɗɗo",
    catTubers: "Yonnde",
    catGrains: "Ganɗal",
    catLegumes: "Kuɓɓe",
    catHerbs: "Caali",
    catDairy: "Kosam",
    aboutProduct: "Dow Nde Nii",
    unit: "Wondirde",
    locationKey: "Nokku",
    deliveryKey: "Artirde",
    delivAvail: "Waawi",
    pickupOnly: "Ar Usee",
    stockKey: "E junngo",
    yourFarmer: "Winndiyanke Maa",
    whatsappSeller: "WhatsApp Winndiyanke",
    moreFarm: "Liɓɓi Ɗowi Ɗuuɗɗi",
    shareProduct: "Siiwtindiraa Nde Nii",
    shareWhatsApp: "Siiwtindiraa WhatsApp",
    freshnessGuarantee: "Ceertol Daneeli",
    freshnessDesc: "So liɓɓi maa wadii yawtini, neldee haala nde 24 waktu.",
    productNotFound: "Liɓɓi Alaa",
    productNotFoundSub: "Liɓɓi hee wudii walla siifaa.",
    backToFarmFresh: "Heddii Liɓɓi Ɗowi",
    orderSummary: "Sarwii Tiimii",
    deliveryAddress: "Nokku Artirde",
    deliveryAddressPlaceholder: "Saare, laawol, waande…",
    contactPhone: "Telefon Maggal",
    orderNotes: "Haala Winndiyanke (seeɗa)",
    orderNotesPlaceholder: "Waktu artirde…",
    placeOrder: "Neld Sarwii",
    orderSuccess: "Sarwii Neldii!",
    orderSuccessSub: "Winndiyanke wiiloyaa maa ko adii.",
    orderError: "Sarwii Waɓɓi",
    demoOrderNote: "Nde misaale.",
    totalAmount: "Timmol",
    transactionFee: "Ñamiri Bambeh (1%)",
    grandTotal: "Timmol Fof",
    sellProduce: "Naattin Liɓɓi Maa",
    step1: "Haala Liɓɓi",
    step2: "Nokku & Janngirde",
    step3: "Sawruuje & Ƴeewtaare",
    productName: "Innde Liɓɓi",
    category: "Daaci",
    pricePerUnit: "Njamndi Koyɗol (FCFA)",
    unitLabel: "Wondirde",
    isOrganic: "Liɓɓi daano / daɗngo",
    availableForDelivery: "Waawi artirde",
    description: "Janngirde",
    descriptionPlaceholder: "Janngir daneeli, taƴre, waktu tokkii…",
    locationLabel: "Nokku Maa (Wuro / Saare)",
    locationPlaceholder: "si'i. Bamenda, Nkwen",
    photos: "Sawruuje (faa 4)",
    addPhoto: "Natt Sawru",
    reviewListing: "Ƴeew & Neld",
    submitListing: "Natt Jayngel",
    listingSuccess: "Jayngel Danɗii!",
    listingSuccessSub: "Liɓɓi maa tawii njiimaaji. Soodooɓe waawi yiyude.",
    saveDraft: "Dann Kabaaru",
    draftSaved: "Kabaaru dannii",
    photoError: "Ko JPG, PNG walla WebP tan, max 5 MB fof.",
    fillRequired2: "Tiim fannu fof heɓɓitaaɗe.",

    cartEmpty: "Sagas maa fotaani",
    cartEmptySub: "Ƴeew jeyɗe naattin nde sagas.",
    continueShopping: "Jokku Sooding",
    checkout: "Ñammbu",
    removeItem: "Haytu",
    subtotal: "Dow",
    fee1pct: "Ñamiri Bambeh (1%)",
    total: "Timmol",
    payWithMoMo: "Ñammbu MTN MoMo",
    payWithOrange: "Ñammbu Orange Money",
    enterPhone: "Naattin Telefon Maa",
    payNow: "Ñammbu Ɗoo",
    paymentPending: "E Yoɓde…",
    paymentPendingSub: "Ƴeew telefon maa, siftinee yoɓde.",
    paymentSuccess: "Yoɓde Danɗii!",
    paymentFailed: "Yoɓde Waɓɓi",
    paymentFailedSub: "Yoɓde maa alaa. Ɓettoo.",

    groupBuyingAdTitle: "Ƴoorgo Sooding — Dannee Fof",
    groupBuyingAdSub: "Naatir sarwiiji fewndo gonooɓe ngel haɗe njamndi.",
    groupBuyingAdCta: "Naatir Ɗoo",
    sellProduceAdTitle: "A Winndiyanke?",
    sellProduceAdSub: "Natt liɓɓi maa ko 3 minti, jooɗiti soodooɓe e Kameruun.",
    sellProduceAdCta: "Fuɗɗo Fiyude",

    voiceSearchFarmFresh: "Ƴeewde Liɓɓi Ɗowi ngam",
    voiceSearchJobs: "Ƴeewde Golle ngam",
    voiceGoTo: "Yah",
    voiceNotFound: "Mi heɓaay. Ƴeew innde liɓɓi walla jayngel.",
  },
};

// ─── Types ─────────────────────────────────────────────────────────────────────
type LanguageCode = "en" | "fr" | "pidgin" | "ar" | "ff";

type LanguageContextType = {
  language: LanguageCode;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  isRtl: boolean;
};

// ─── Context ───────────────────────────────────────────────────────────────────
const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
  isRtl: false,
});

// ─── Storage key — unified across the entire app ───────────────────────────────
const LANG_KEY = "Bambeh_language";

function resolveCode(raw: string | null): LanguageCode {
  const valid: LanguageCode[] = ["en", "fr", "pidgin", "ar", "ff"];
  // Accept aliases used by older LanguageSelection versions
  if (raw === "pcm" || raw === "pidgin_english") return "pidgin";
  if (raw === "ful" || raw === "fulfulde")        return "ff";
  if (valid.includes(raw as LanguageCode)) return raw as LanguageCode;
  return "en";
}

// ─── Provider ──────────────────────────────────────────────────────────────────
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<LanguageCode>(() =>
    resolveCode(localStorage.getItem(LANG_KEY))
  );

  const applyDocumentAttrs = useCallback((lang: LanguageCode) => {
    document.documentElement.dir  = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, []);

  useEffect(() => {
    applyDocumentAttrs(language);

    // Sync across tabs / other parts of the app that write to localStorage
    const handleStorage = (e: StorageEvent) => {
      if (e.key === LANG_KEY && e.newValue) {
        const next = resolveCode(e.newValue);
        setLanguageState(next);
        applyDocumentAttrs(next);
      }
    };
    window.addEventListener("storage", handleStorage);
    return () => window.removeEventListener("storage", handleStorage);
  }, [language, applyDocumentAttrs]);

  const setLanguage = useCallback(
    (lang: string) => {
      const next = resolveCode(lang);
      setLanguageState(next);
      localStorage.setItem(LANG_KEY, next);
      applyDocumentAttrs(next);
    },
    [applyDocumentAttrs]
  );

  const t = useCallback(
    (key: string): string =>
      translations[language]?.[key] ??
      translations["en"]?.[key] ??
      key,
    [language]
  );

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t, isRtl: language === "ar" }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);






