/**
 * src/context/LanguageContext.tsx — Bambeh Marketplace
 * ✅ Uses unified key: "Bambeh_language" (matches LanguageSelection.tsx)
 * ✅ Full translations: EN / FR / Pidgin / AR / FF (Fulfulde)
 * ✅ Covers all UI keys including FarmFresh, categories, cart, payments
 * © 2025–2026 BAMBEH SARL. All rights reserved.
 */

import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

// ─── Translation map ──────────────────────────────────────────────────────────
const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    home: "Home",
    jobs: "Jobs",
    marketplace: "Marketplace",
    services: "Services",
    rentals: "Rentals",
    vehicles: "Vehicles",
    exchange: "Exchange",
    community: "Community",
    sell: "Sell",
    buy: "Buy",
    search: "Search",
    login: "Login",
    register: "Register",
    logout: "Logout",
    settings: "Settings",
    favorites: "Favorites",
    orders: "Orders",
    next: "Next",
    submit: "Submit",
    back: "Back",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    loading: "Loading…",
    error: "Something went wrong. Please try again.",
    retry: "Retry",
    seeAll: "See all",

    // FarmFresh page
    farmFresh: "Farm Fresh",
    farmFreshSub: "Fresh produce direct from Cameroonian farmers",
    searchPlaceholder: "Search produce, location…",
    noProduceFound: "No produce found",
    noProduceFoundSub: "Try a different search or category, or be the first to list!",
    listYourProduce: "List Your Produce",
    showingSamples: "Showing sample listings",
    realListings: "listings available from local farmers",
    buyDirect: "Buy Direct From Farmers",
    buyDirectSub: "Fresh produce, fair prices, from farm to your table in Cameroon.",
    joinGroup: "Join Group Buy",
    organic: "Organic",
    noPhotoYet: "No photo yet",
    addToCart: "Add to Cart",
    added: "Added ✓",
    views: "views",
    cart: "Cart",
    orderNow: "Order Now",
    quantity: "Qty",

    // FarmFresh categories
    catAll: "All",
    catVegetables: "Vegetables",
    catFruits: "Fruits",
    catTubers: "Tubers",
    catGrains: "Grains",
    catLegumes: "Legumes",
    catHerbs: "Herbs",
    catDairy: "Dairy",

    // FarmFresh detail
    aboutProduct: "About This Product",
    unit: "Unit",
    locationKey: "Location",
    deliveryKey: "Delivery",
    delivAvail: "Available",
    pickupOnly: "Pickup only",
    stockKey: "In Stock",
    yourFarmer: "Your Farmer",
    whatsappSeller: "WhatsApp Farmer",
    moreFarm: "More Farm Products",
    shareProduct: "Share This Product",
    shareWhatsApp: "Share on WhatsApp",
    copyLink: "Copy Link",
    freshnessGuarantee: "Freshness Guarantee",
    freshnessDesc: "If your produce arrives below standard, report within 24 hours and we'll arrange a replacement or full refund.",
    productNotFound: "Product Not Found",
    productNotFoundSub: "This product may be unavailable or has been removed.",
    backToFarmFresh: "Back to Farm Fresh",

    // FarmFresh order
    orderSummary: "Order Summary",
    deliveryAddress: "Delivery Address",
    deliveryAddressPlaceholder: "Quarter, street, landmark…",
    contactPhone: "Contact Phone",
    orderNotes: "Notes for Farmer (optional)",
    orderNotesPlaceholder: "Preferred delivery time, special instructions…",
    placeOrder: "Place Order",
    orderSuccess: "Order Placed!",
    orderSuccessSub: "The farmer will contact you shortly to confirm delivery.",
    orderError: "Order Failed",
    demoOrderNote: "This is a demo product. In production your order will be sent to a real farmer.",
    totalAmount: "Total",
    transactionFee: "Transaction Fee (1%)",
    grandTotal: "Grand Total",

    // FarmFresh seller
    sellProduce: "List Your Produce",
    step1: "Produce Details",
    step2: "Location & Description",
    step3: "Photos & Review",
    productName: "Product Name",
    category: "Category",
    pricePerUnit: "Price per Unit (FCFA)",
    unitLabel: "Unit",
    isOrganic: "This produce is organic / naturally grown",
    availableForDelivery: "Available for delivery",
    description: "Description",
    descriptionPlaceholder: "Describe freshness, quality, harvest date, growing method…",
    locationLabel: "Your Location (Town / Quarter)",
    locationPlaceholder: "e.g. Bamenda, Nkwen Quarter",
    photos: "Photos (up to 4)",
    addPhoto: "Add Photo",
    reviewListing: "Review & Submit",
    submitListing: "Post Listing",
    listingSuccess: "Listing Published!",
    listingSuccessSub: "Your produce is now live. Buyers can see and order it.",
    saveDraft: "Save Draft",
    draftSaved: "Draft saved",
    photoError: "Only JPG, PNG or WebP images, max 5 MB each.",
    fillRequired: "Please fill in all required fields.",

    // Cart & Payment
    cartEmpty: "Your cart is empty",
    cartEmptySub: "Browse listings and add items to your cart.",
    continueShopping: "Continue Shopping",
    checkout: "Checkout",
    removeItem: "Remove",
    subtotal: "Subtotal",
    fee1pct: "Bambeh Fee (1%)",
    total: "Total",
    payWithMoMo: "Pay with MTN MoMo",
    payWithOrange: "Pay with Orange Money",
    enterPhone: "Enter your mobile number",
    payNow: "Pay Now",
    paymentPending: "Payment Pending",
    paymentPendingSub: "Check your phone and approve the payment prompt.",
    paymentSuccess: "Payment Successful!",
    paymentFailed: "Payment Failed",
    paymentFailedSub: "Your payment was not completed. Please try again.",

    // Ad slots
    groupBuyingAdTitle: "Group Buying — Save Together",
    groupBuyingAdSub: "Pool orders with neighbours and get better prices.",
    groupBuyingAdCta: "Join Now",
    sellProduceAdTitle: "Are You a Farmer?",
    sellProduceAdSub: "List your produce in 3 minutes and reach buyers across Cameroon.",
    sellProduceAdCta: "Start Selling",

    // Voice control
    voiceSearchFarmFresh: "Searching Farm Fresh for",
    voiceGoTo: "Going to",
    voiceNotFound: "I couldn't find that. Try saying a product name or page.",
  },

  fr: {
    home: "Accueil",
    jobs: "Emplois",
    marketplace: "Marché",
    services: "Services",
    rentals: "Locations",
    vehicles: "Véhicules",
    exchange: "Échange",
    community: "Communauté",
    sell: "Vendre",
    buy: "Acheter",
    search: "Rechercher",
    login: "Connexion",
    register: "S'inscrire",
    logout: "Déconnexion",
    settings: "Paramètres",
    favorites: "Favoris",
    orders: "Commandes",
    next: "Suivant",
    submit: "Soumettre",
    back: "Retour",
    cancel: "Annuler",
    save: "Enregistrer",
    edit: "Modifier",
    delete: "Supprimer",
    confirm: "Confirmer",
    loading: "Chargement…",
    error: "Une erreur est survenue. Veuillez réessayer.",
    retry: "Réessayer",
    seeAll: "Voir tout",

    farmFresh: "Ferme Fraîche",
    farmFreshSub: "Produits frais directement des agriculteurs camerounais",
    searchPlaceholder: "Chercher un produit, une ville…",
    noProduceFound: "Aucun produit trouvé",
    noProduceFoundSub: "Essayez une autre recherche ou soyez le premier à publier!",
    listYourProduce: "Publier votre produit",
    showingSamples: "Exemples de produits",
    realListings: "produits disponibles d'agriculteurs locaux",
    buyDirect: "Achetez Directement aux Agriculteurs",
    buyDirectSub: "Produits frais, prix équitables, de la ferme à votre table.",
    joinGroup: "Rejoindre un groupe d'achat",
    organic: "Bio",
    noPhotoYet: "Pas de photo",
    addToCart: "Ajouter au panier",
    added: "Ajouté ✓",
    views: "vues",
    cart: "Panier",
    orderNow: "Commander",
    quantity: "Qté",

    catAll: "Tout",
    catVegetables: "Légumes",
    catFruits: "Fruits",
    catTubers: "Tubercules",
    catGrains: "Céréales",
    catLegumes: "Légumineuses",
    catHerbs: "Herbes",
    catDairy: "Produits laitiers",

    aboutProduct: "À propos du produit",
    unit: "Unité",
    locationKey: "Lieu",
    deliveryKey: "Livraison",
    delivAvail: "Disponible",
    pickupOnly: "Récupération uniquement",
    stockKey: "En stock",
    yourFarmer: "Votre Agriculteur",
    whatsappSeller: "WhatsApp Agriculteur",
    moreFarm: "Plus de produits agricoles",
    shareProduct: "Partager ce produit",
    shareWhatsApp: "Partager sur WhatsApp",
    copyLink: "Copier le lien",
    freshnessGuarantee: "Garantie de fraîcheur",
    freshnessDesc: "Si vos produits arrivent en dessous de nos standards, signalez-le en 24 h et nous organiserons un remplacement ou un remboursement complet.",
    productNotFound: "Produit introuvable",
    productNotFoundSub: "Ce produit est peut-être indisponible ou supprimé.",
    backToFarmFresh: "Retour à Ferme Fraîche",

    orderSummary: "Récapitulatif de commande",
    deliveryAddress: "Adresse de livraison",
    deliveryAddressPlaceholder: "Quartier, rue, point de repère…",
    contactPhone: "Téléphone de contact",
    orderNotes: "Notes pour l'agriculteur (facultatif)",
    orderNotesPlaceholder: "Heure de livraison préférée, instructions spéciales…",
    placeOrder: "Passer la commande",
    orderSuccess: "Commande passée !",
    orderSuccessSub: "L'agriculteur vous contactera bientôt pour confirmer la livraison.",
    orderError: "Échec de la commande",
    demoOrderNote: "Ceci est un produit de démonstration.",
    totalAmount: "Total",
    transactionFee: "Frais Bambeh (1 %)",
    grandTotal: "Total général",

    sellProduce: "Publier votre produit",
    step1: "Détails du produit",
    step2: "Lieu & Description",
    step3: "Photos & Vérification",
    productName: "Nom du produit",
    category: "Catégorie",
    pricePerUnit: "Prix par unité (FCFA)",
    unitLabel: "Unité",
    isOrganic: "Ce produit est biologique / cultivé naturellement",
    availableForDelivery: "Disponible pour la livraison",
    description: "Description",
    descriptionPlaceholder: "Décrivez la fraîcheur, la qualité, la date de récolte…",
    locationLabel: "Votre lieu (Ville / Quartier)",
    locationPlaceholder: "ex. Bafoussam, Quartier Tamdja",
    photos: "Photos (jusqu'à 4)",
    addPhoto: "Ajouter une photo",
    reviewListing: "Vérifier et soumettre",
    submitListing: "Publier l'annonce",
    listingSuccess: "Annonce publiée !",
    listingSuccessSub: "Votre produit est maintenant visible. Les acheteurs peuvent le voir et le commander.",
    saveDraft: "Sauvegarder le brouillon",
    draftSaved: "Brouillon sauvegardé",
    photoError: "Seulement JPG, PNG ou WebP, max 5 Mo chacun.",
    fillRequired: "Veuillez remplir tous les champs obligatoires.",

    cartEmpty: "Votre panier est vide",
    cartEmptySub: "Parcourez les annonces et ajoutez des articles à votre panier.",
    continueShopping: "Continuer les achats",
    checkout: "Passer à la caisse",
    removeItem: "Retirer",
    subtotal: "Sous-total",
    fee1pct: "Frais Bambeh (1 %)",
    total: "Total",
    payWithMoMo: "Payer avec MTN MoMo",
    payWithOrange: "Payer avec Orange Money",
    enterPhone: "Entrez votre numéro de téléphone mobile",
    payNow: "Payer maintenant",
    paymentPending: "Paiement en attente",
    paymentPendingSub: "Vérifiez votre téléphone et approuvez la demande de paiement.",
    paymentSuccess: "Paiement réussi !",
    paymentFailed: "Paiement échoué",
    paymentFailedSub: "Votre paiement n'a pas abouti. Veuillez réessayer.",

    groupBuyingAdTitle: "Achat groupé — Économisez ensemble",
    groupBuyingAdSub: "Groupez vos commandes avec vos voisins pour de meilleurs prix.",
    groupBuyingAdCta: "Rejoindre",
    sellProduceAdTitle: "Vous êtes agriculteur ?",
    sellProduceAdSub: "Publiez vos produits en 3 minutes et atteignez les acheteurs partout au Cameroun.",
    sellProduceAdCta: "Commencer à vendre",

    voiceSearchFarmFresh: "Recherche dans Ferme Fraîche pour",
    voiceGoTo: "Navigation vers",
    voiceNotFound: "Je n'ai pas trouvé cela. Essayez un nom de produit ou de page.",
  },

  pidgin: {
    home: "Home",
    jobs: "Jobs",
    marketplace: "Market",
    services: "Services",
    rentals: "Rentals",
    vehicles: "Cars",
    exchange: "Exchange",
    community: "Community",
    sell: "Sell",
    buy: "Buy",
    search: "Search",
    login: "Login",
    register: "Register",
    logout: "Logout",
    settings: "Settings",
    favorites: "Favorites",
    orders: "Orders",
    next: "Next",
    submit: "Submit",
    back: "Back",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    loading: "E dey load…",
    error: "Something spoil. Try again.",
    retry: "Try Again",
    seeAll: "See all",

    farmFresh: "Farm Fresh",
    farmFreshSub: "Fresh tins direct from Cameroon farmers",
    searchPlaceholder: "Find food, place…",
    noProduceFound: "No food dey here",
    noProduceFoundSub: "Try different search or be first person post something!",
    listYourProduce: "List Your Tins",
    showingSamples: "Sample listings dey show",
    realListings: "listings dey from local farmers",
    buyDirect: "Buy Direct From Farmer",
    buyDirectSub: "Fresh food, good price, from farm reach your house.",
    joinGroup: "Join Group Buy",
    organic: "Organic",
    noPhotoYet: "No photo yet",
    addToCart: "Add for Cart",
    added: "E dey inside ✓",
    views: "views",
    cart: "Cart",
    orderNow: "Order Now",
    quantity: "How Many",

    catAll: "All",
    catVegetables: "Vegetables",
    catFruits: "Fruits",
    catTubers: "Tubers",
    catGrains: "Grains",
    catLegumes: "Legumes",
    catHerbs: "Herbs",
    catDairy: "Dairy",

    aboutProduct: "About Dis Tin",
    unit: "Unit",
    locationKey: "Place",
    deliveryKey: "Delivery",
    delivAvail: "Dey available",
    pickupOnly: "Come take am",
    stockKey: "Quantity for hand",
    yourFarmer: "Your Farmer",
    whatsappSeller: "WhatsApp the Farmer",
    moreFarm: "More Farm Tins",
    shareProduct: "Share Dis Tin",
    shareWhatsApp: "Share for WhatsApp",
    copyLink: "Copy Link",
    freshnessGuarantee: "Freshness Guarantee",
    freshnessDesc: "If your food no fresh when e reach, report am for 24 hours, we go change am or give you back your money.",
    productNotFound: "Dis product no dey",
    productNotFoundSub: "E don remove or e no available again.",
    backToFarmFresh: "Back to Farm Fresh",

    orderSummary: "Order Summary",
    deliveryAddress: "Where dem go bring am",
    deliveryAddressPlaceholder: "Quarter, street, landmark…",
    contactPhone: "Your phone number",
    orderNotes: "Tell farmer something (optional)",
    orderNotesPlaceholder: "When you want am, special request…",
    placeOrder: "Place Order",
    orderSuccess: "Order Don Go!",
    orderSuccessSub: "Farmer go call you soon to confirm delivery.",
    orderError: "Order fail",
    demoOrderNote: "Na demo product dis one.",
    totalAmount: "Total",
    transactionFee: "Bambeh Fee (1%)",
    grandTotal: "Grand Total",

    sellProduce: "Post Your Produce",
    step1: "Product Details",
    step2: "Place & Description",
    step3: "Photos & Review",
    productName: "Product Name",
    category: "Category",
    pricePerUnit: "Price for one unit (FCFA)",
    unitLabel: "Unit",
    isOrganic: "Na organic / natural food",
    availableForDelivery: "You fit deliver am",
    description: "Description",
    descriptionPlaceholder: "Talk about how fresh, quality, when dem harvest am…",
    locationLabel: "Your Place (Town / Quarter)",
    locationPlaceholder: "e.g. Bamenda, Nkwen Quarter",
    photos: "Photos (up to 4)",
    addPhoto: "Add Photo",
    reviewListing: "Check and Submit",
    submitListing: "Post Am",
    listingSuccess: "Listing Done Post!",
    listingSuccessSub: "Your produce dey live. Buyers go see am.",
    saveDraft: "Save Draft",
    draftSaved: "Draft saved",
    photoError: "Only JPG, PNG or WebP, max 5 MB each.",
    fillRequired: "Fill all the required fields abeg.",

    cartEmpty: "Your cart empty",
    cartEmptySub: "Browse and add tins for your cart.",
    continueShopping: "Continue Shopping",
    checkout: "Go Pay",
    removeItem: "Remove",
    subtotal: "Subtotal",
    fee1pct: "Bambeh Fee (1%)",
    total: "Total",
    payWithMoMo: "Pay with MTN MoMo",
    payWithOrange: "Pay with Orange Money",
    enterPhone: "Enter your phone number",
    payNow: "Pay Now",
    paymentPending: "Payment Pending",
    paymentPendingSub: "Check your phone, approve the payment.",
    paymentSuccess: "Payment Don Enter!",
    paymentFailed: "Payment Fail",
    paymentFailedSub: "Your payment no go through. Try again.",

    groupBuyingAdTitle: "Group Buy — Save Together",
    groupBuyingAdSub: "Pool orders with your people for better prices.",
    groupBuyingAdCta: "Join Now",
    sellProduceAdTitle: "You be Farmer?",
    sellProduceAdSub: "Post your produce for 3 minutes, reach buyers all over Cameroon.",
    sellProduceAdCta: "Start Sell",

    voiceSearchFarmFresh: "Searching Farm Fresh for",
    voiceGoTo: "Going to",
    voiceNotFound: "I no find am. Try product name or page name.",
  },

  ar: {
    home: "الرئيسية",
    jobs: "الوظائف",
    marketplace: "السوق",
    services: "الخدمات",
    rentals: "الإيجارات",
    vehicles: "المركبات",
    exchange: "التبادل",
    community: "المجتمع",
    sell: "بيع",
    buy: "شراء",
    search: "بحث",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    settings: "الإعدادات",
    favorites: "المفضلة",
    orders: "الطلبات",
    next: "التالي",
    submit: "إرسال",
    back: "رجوع",
    cancel: "إلغاء",
    save: "حفظ",
    edit: "تعديل",
    delete: "حذف",
    confirm: "تأكيد",
    loading: "جارٍ التحميل…",
    error: "حدث خطأ. يرجى المحاولة مجدداً.",
    retry: "إعادة المحاولة",
    seeAll: "عرض الكل",

    farmFresh: "منتجات الحقل الطازجة",
    farmFreshSub: "منتجات طازجة مباشرة من مزارعي الكاميرون",
    searchPlaceholder: "ابحث عن منتج أو موقع…",
    noProduceFound: "لا توجد منتجات",
    noProduceFoundSub: "جرّب بحثاً آخر أو كن أول من ينشر!",
    listYourProduce: "أضف منتجك",
    showingSamples: "عرض نماذج المنتجات",
    realListings: "منتجات متاحة من المزارعين المحليين",
    buyDirect: "اشترِ مباشرة من المزارع",
    buyDirectSub: "منتجات طازجة وأسعار عادلة من المزرعة إلى مائدتك.",
    joinGroup: "انضم للشراء الجماعي",
    organic: "عضوي",
    noPhotoYet: "لا توجد صورة",
    addToCart: "أضف إلى السلة",
    added: "تمت الإضافة ✓",
    views: "مشاهدات",
    cart: "السلة",
    orderNow: "اطلب الآن",
    quantity: "الكمية",

    catAll: "الكل",
    catVegetables: "خضروات",
    catFruits: "فواكه",
    catTubers: "درنات",
    catGrains: "حبوب",
    catLegumes: "بقوليات",
    catHerbs: "أعشاب",
    catDairy: "منتجات الألبان",

    aboutProduct: "حول هذا المنتج",
    unit: "الوحدة",
    locationKey: "الموقع",
    deliveryKey: "التوصيل",
    delivAvail: "متاح",
    pickupOnly: "الاستلام الشخصي فقط",
    stockKey: "المخزون",
    yourFarmer: "مزارعك",
    whatsappSeller: "تواصل مع المزارع عبر واتساب",
    moreFarm: "مزيد من المنتجات الزراعية",
    shareProduct: "مشاركة هذا المنتج",
    shareWhatsApp: "مشاركة على واتساب",
    copyLink: "نسخ الرابط",
    freshnessGuarantee: "ضمان النضارة",
    freshnessDesc: "إذا وصلت منتجاتك دون المستوى، أبلغ عن ذلك خلال 24 ساعة وسنرتب استبداله أو استرداد المبلغ كاملاً.",
    productNotFound: "المنتج غير موجود",
    productNotFoundSub: "قد يكون هذا المنتج غير متاح أو تم حذفه.",
    backToFarmFresh: "العودة إلى منتجات الحقل",

    orderSummary: "ملخص الطلب",
    deliveryAddress: "عنوان التوصيل",
    deliveryAddressPlaceholder: "الحي، الشارع، معلم قريب…",
    contactPhone: "رقم الهاتف للتواصل",
    orderNotes: "ملاحظات للمزارع (اختياري)",
    orderNotesPlaceholder: "وقت التسليم المفضل، تعليمات خاصة…",
    placeOrder: "تأكيد الطلب",
    orderSuccess: "تم تقديم الطلب!",
    orderSuccessSub: "سيتواصل معك المزارع قريباً لتأكيد التوصيل.",
    orderError: "فشل تقديم الطلب",
    demoOrderNote: "هذا منتج تجريبي.",
    totalAmount: "الإجمالي",
    transactionFee: "رسوم بامبيه (1٪)",
    grandTotal: "الإجمالي الكلي",

    sellProduce: "أضف منتجك",
    step1: "تفاصيل المنتج",
    step2: "الموقع والوصف",
    step3: "الصور والمراجعة",
    productName: "اسم المنتج",
    category: "الفئة",
    pricePerUnit: "السعر لكل وحدة (FCFA)",
    unitLabel: "الوحدة",
    isOrganic: "هذا المنتج عضوي / مزروع طبيعياً",
    availableForDelivery: "متاح للتوصيل",
    description: "الوصف",
    descriptionPlaceholder: "صف الجودة وتاريخ الحصاد وطريقة الزراعة…",
    locationLabel: "موقعك (المدينة / الحي)",
    locationPlaceholder: "مثال: ياوندي، حي الجامعة",
    photos: "الصور (حتى 4)",
    addPhoto: "إضافة صورة",
    reviewListing: "مراجعة وإرسال",
    submitListing: "نشر الإعلان",
    listingSuccess: "تم نشر الإعلان!",
    listingSuccessSub: "منتجك الآن ظاهر للمشترين.",
    saveDraft: "حفظ المسودة",
    draftSaved: "تم حفظ المسودة",
    photoError: "يُسمح فقط بصور JPG أو PNG أو WebP، بحد أقصى 5 ميغابايت.",
    fillRequired: "يرجى ملء جميع الحقول المطلوبة.",

    cartEmpty: "سلتك فارغة",
    cartEmptySub: "تصفح الإعلانات وأضف ما تريد إلى سلتك.",
    continueShopping: "متابعة التسوق",
    checkout: "إتمام الشراء",
    removeItem: "إزالة",
    subtotal: "المجموع الجزئي",
    fee1pct: "رسوم بامبيه (1٪)",
    total: "الإجمالي",
    payWithMoMo: "الدفع عبر MTN MoMo",
    payWithOrange: "الدفع عبر Orange Money",
    enterPhone: "أدخل رقم هاتفك المحمول",
    payNow: "ادفع الآن",
    paymentPending: "في انتظار الدفع",
    paymentPendingSub: "تحقق من هاتفك وأقرّ طلب الدفع.",
    paymentSuccess: "تم الدفع بنجاح!",
    paymentFailed: "فشل الدفع",
    paymentFailedSub: "لم يكتمل دفعك. يرجى المحاولة مجدداً.",

    groupBuyingAdTitle: "الشراء الجماعي — وفّروا معاً",
    groupBuyingAdSub: "جمّعوا طلباتكم مع الجيران للحصول على أسعار أفضل.",
    groupBuyingAdCta: "انضم الآن",
    sellProduceAdTitle: "هل أنت مزارع؟",
    sellProduceAdSub: "أضف منتجاتك في 3 دقائق وصل إلى المشترين في الكاميرون.",
    sellProduceAdCta: "ابدأ البيع",

    voiceSearchFarmFresh: "البحث في منتجات الحقل عن",
    voiceGoTo: "الانتقال إلى",
    voiceNotFound: "لم أتمكن من العثور على ذلك. جرّب اسم منتج أو صفحة.",
  },

  ff: {
    home: "Jeyeendi",
    jobs: "Liggaade",
    marketplace: "Maare",
    services: "Ɓalɗe",
    rentals: "Hireeli",
    vehicles: "Ottooji",
    exchange: "Yoƴtaari",
    community: "Ɓiɓɓe",
    sell: "Fiyee",
    buy: "Soodee",
    search: "Ƴeewee",
    login: "Naatdee",
    register: "Restoree",
    logout: "Fuɗɗodee",
    settings: "Haɓɓitorde",
    favorites: "Faaɓaaɓe",
    orders: "Sarwiiji",
    next: "Ɓurngo",
    submit: "Neldee",
    back: "Heddii",
    cancel: "Haɗ",
    save: "Dannee",
    edit: "Rewindee",
    delete: "Siftoo",
    confirm: "Siftinee",
    loading: "E nder loodi…",
    error: "Huunde booɗɗuɗe waɓɓi. Ɓettoo.",
    retry: "Ɓettoo",
    seeAll: "Hol fof",

    farmFresh: "Liɓɓi Ɗowi",
    farmFreshSub: "Liɓɓi daneeli fewndo winndiyanke Kamerun",
    searchPlaceholder: "Ƴeew liɓɓi, gure…",
    noProduceFound: "Liɓɓi alaa",
    noProduceFoundSub: "Ƴeew koɗum walla fuɗɗo jayngel!",
    listYourProduce: "Naattin Liɓɓi Maa",
    showingSamples: "Misaale liɓɓi",
    realListings: "liɓɓi daneeli winndiyankeeɓe",
    buyDirect: "Soodee Fewndo Winndiyanke",
    buyDirectSub: "Liɓɓi daneeli, njamndi yooɓii, fewndo ladde resta taabal maa.",
    joinGroup: "Naatir Ƴoorgo",
    organic: "Daano",
    noPhotoYet: "Sawru alaa",
    addToCart: "Naattin Sagas",
    added: "E nder ✓",
    views: "yiyiiko",
    cart: "Sagas",
    orderNow: "Sarwii Ɗoo",
    quantity: "Timmol",

    catAll: "Fof",
    catVegetables: "Leɗɗe",
    catFruits: "Biɗɗo",
    catTubers: "Yonnde",
    catGrains: "Ganɗal",
    catLegumes: "Kuɓɓe",
    catHerbs: "Caali",
    catDairy: "Kosam",

    aboutProduct: "Dow Nde Nii",
    unit: "Wondirde",
    locationKey: "Nokku",
    deliveryKey: "Artirde",
    delivAvail: "Waawi",
    pickupOnly: "Ar Usee",
    stockKey: "E junngo",
    yourFarmer: "Winndiyanke Maa",
    whatsappSeller: "WhatsApp Winndiyanke",
    moreFarm: "Liɓɓi Ɗowi Ɗuuɗɗi",
    shareProduct: "Siiwtindiraa Nde Nii",
    shareWhatsApp: "Siiwtindiraa WhatsApp",
    copyLink: "Natto Laawol",
    freshnessGuarantee: "Ceertol Daneeli",
    freshnessDesc: "So liɓɓi maa wadii yawtini, neldee haala nde 24 waktu, min neldoyii walla neldoytaa koɓɓal.",
    productNotFound: "Liɓɓi Alaa",
    productNotFoundSub: "Liɓɓi hee wudii walla siifaa.",
    backToFarmFresh: "Heddii Liɓɓi Ɗowi",

    orderSummary: "Sarwii Tiimii",
    deliveryAddress: "Nokku Artirde",
    deliveryAddressPlaceholder: "Saare, laawol, waande…",
    contactPhone: "Telefon Maggal",
    orderNotes: "Haala Winndiyanke (seeɗa)",
    orderNotesPlaceholder: "Waktu artirde, sarwiiji fof…",
    placeOrder: "Neld Sarwii",
    orderSuccess: "Sarwii Neldii!",
    orderSuccessSub: "Winndiyanke wiiloyaa maa ko adii.",
    orderError: "Sarwii Waɓɓi",
    demoOrderNote: "Nde misaale.",
    totalAmount: "Timmol",
    transactionFee: "Ñamiri Bambeh (1%)",
    grandTotal: "Timmol Fof",

    sellProduce: "Naattin Liɓɓi Maa",
    step1: "Haala Liɓɓi",
    step2: "Nokku & Janngirde",
    step3: "Sawruuje & Ƴeewtaare",
    productName: "Innde Liɓɓi",
    category: "Daaci",
    pricePerUnit: "Njamndi Koyɗol (FCFA)",
    unitLabel: "Wondirde",
    isOrganic: "Liɓɓi daano / daɗngo",
    availableForDelivery: "Waawi artirde",
    description: "Janngirde",
    descriptionPlaceholder: "Janngir daneeli, taƴre, waktu tokkii…",
    locationLabel: "Nokku Maa (Wuro / Saare)",
    locationPlaceholder: "si'i. Bamenda, Nkwen",
    photos: "Sawruuje (faa 4)",
    addPhoto: "Natt Sawru",
    reviewListing: "Ƴeew & Neld",
    submitListing: "Natt Jayngel",
    listingSuccess: "Jayngel Danɗii!",
    listingSuccessSub: "Liɓɓi maa tawii njiimaaji. Soodooɓe waawi yiyude.",
    saveDraft: "Dann Kabaaru",
    draftSaved: "Kabaaru dannii",
    photoError: "Ko JPG, PNG walla WebP tan, max 5 MB fof.",
    fillRequired: "Tiim fannu fof heɓɓitaaɗe.",

    cartEmpty: "Sagas maa fotaani",
    cartEmptySub: "Ƴeew jeyɗe naattin nde sagas.",
    continueShopping: "Jokku Sooding",
    checkout: "Ñammbu",
    removeItem: "Haytu",
    subtotal: "Dow",
    fee1pct: "Ñamiri Bambeh (1%)",
    total: "Timmol",
    payWithMoMo: "Ñammbu MTN MoMo",
    payWithOrange: "Ñammbu Orange Money",
    enterPhone: "Naattin Telefon Maa",
    payNow: "Ñammbu Ɗoo",
    paymentPending: "E Yoɓde…",
    paymentPendingSub: "Ƴeew telefon maa, siftinee yoɓde.",
    paymentSuccess: "Yoɓde Danɗii!",
    paymentFailed: "Yoɓde Waɓɓi",
    paymentFailedSub: "Yoɓde maa alaa. Ɓettoo.",

    groupBuyingAdTitle: "Ƴoorgo Sooding — Dannee Fof",
    groupBuyingAdSub: "Naatir sarwiiji fewndo gonooɓe ngel haɗe njamndi.",
    groupBuyingAdCta: "Naatir Ɗoo",
    sellProduceAdTitle: "A Winndiyanke?",
    sellProduceAdSub: "Natt liɓɓi maa ko 3 minti, jooɗiti soodooɓe e Kamerun.",
    sellProduceAdCta: "Fuɗɗo Fiyude",

    voiceSearchFarmFresh: "Ƴeewde Liɓɓi Ɗowi ngam",
    voiceGoTo: "Yah",
    voiceNotFound: "Mi heɓaay. Ƴeew innde liɓɓi walla jayngel.",
  },
};

// ─── Types ────────────────────────────────────────────────────────────────────
type LanguageCode = "en" | "fr" | "pidgin" | "ar" | "ff";

type LanguageContextType = {
  language: LanguageCode;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  isRtl: boolean;
};

// ─── Context ──────────────────────────────────────────────────────────────────
const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
  isRtl: false,
});

// ─── Storage key — unified across the entire app ──────────────────────────────
const LANG_KEY = "Bambeh_language";

function resolveCode(raw: string | null): LanguageCode {
  const valid: LanguageCode[] = ["en", "fr", "pidgin", "ar", "ff"];
  // Accept "pcm" as an alias for Pidgin (used in some older LanguageSelection versions)
  if (raw === "pcm") return "pidgin";
  if (valid.includes(raw as LanguageCode)) return raw as LanguageCode;
  return "en";
}

// ─── Provider ─────────────────────────────────────────────────────────────────
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<LanguageCode>(() =>
    resolveCode(localStorage.getItem(LANG_KEY))
  );

  // Keep document dir / lang attribute in sync
  const applyDocumentAttrs = useCallback((lang: LanguageCode) => {
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, []);

  useEffect(() => {
    applyDocumentAttrs(language);

    // Listen for language changes made by LanguageSelection / LanguageSwitcher
    // so that all mounted tabs update simultaneously.
    const handleStorage = (e: StorageEvent) => {
      if (e.key === LANG_KEY && e.newValue) {
        const next = resolveCode(e.newValue);
        setLanguageState(next);
        applyDocumentAttrs(next);
      }
    };

    window.addEventListener("storage", handleStorage);
    return () => window.removeEventListener("storage", handleStorage);
  }, [language, applyDocumentAttrs]);

  const setLanguage = useCallback(
    (lang: string) => {
      const next = resolveCode(lang);
      setLanguageState(next);
      localStorage.setItem(LANG_KEY, next);
      applyDocumentAttrs(next);
    },
    [applyDocumentAttrs]
  );

  const t = useCallback(
    (key: string): string =>
      translations[language]?.[key] ??
      translations["en"]?.[key] ??
      key,
    [language]
  );

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t, isRtl: language === "ar" }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

// ─── Convenience re-export compatible with the existing useAppLang hook ───────
// Many files import { useLang, t } from "@/hooks/useAppLang".
// Drop this file at src/hooks/useAppLang.ts to bridge them:
//
//   import { useLanguage } from "@/context/LanguageContext";
//   export const useLang = () => useLanguage().language;
//   export const t = (key: string, lang: string): string => {
//     // Use the context t() from inside a component instead
//   };
